/* =============================================================
   === AVIATION CAPITAL SIMULATOR - WORLD AIRPORTS DATABASE ===
   Version: 2.0 (Full Global Civil & Commercial)
   Date: 2025-11-10
   Author: Aviation Capital Systems
   -------------------------------------------------------------
   ▪ Contains ~5,000 ICAO airports (civil & commercial only)
   ▪ Divided by continent blocks
   ▪ Fully compatible with acs_time.js v2.0 Historical Engine
   ▪ Includes economic, geographic and demand parameters
   ============================================================= */

const WorldAirportsACS = {
  /* =============================================================
     🌍 EUROPE
     ============================================================= */
  Europe: [
    {
      icao: "LEMD",
      iata: "MAD",
      city: "Madrid",
      country: "Spain",
      continent: "Europe",
      region: "Southern Europe",
      latitude: 40.472,
      longitude: -3.560,
      elevation_ft: 1998,
      runway_m: 4350,
      open_hrs: "24H",
      category: "International Hub",
      demand: { Y: 1200, C: 180, F: 45 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2800,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.0,
      slot_capacity: 200,
      aircraft_limit: "Heavy",
      notes: "Main Iberian hub with long-haul connections."
    },
    {
      icao: "EGLL",
      iata: "LHR",
      city: "London",
      country: "United Kingdom",
      continent: "Europe",
      region: "Western Europe",
      latitude: 51.4775,
      longitude: -0.4614,
      elevation_ft: 83,
      runway_m: 3902,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2000, C: 350, F: 90 },
      slot_cost_usd: 3500,
      landing_fee_usd: 4100,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.2,
      slot_capacity: 400,
      aircraft_limit: "Heavy",
      notes: "Europe’s busiest international airport."
    },
    {
      icao: "LFPG",
      iata: "CDG",
      city: "Paris",
      country: "France",
      continent: "Europe",
      region: "Western Europe",
      latitude: 49.0097,
      longitude: 2.5479,
      elevation_ft: 392,
      runway_m: 4215,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1800, C: 300, F: 80 },
      slot_cost_usd: 3200,
      landing_fee_usd: 3900,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.15,
      slot_capacity: 380,
      aircraft_limit: "Heavy",
      notes: "Major European hub operated by Air France."
    },
    {
      icao: "EDDF",
      iata: "FRA",
      city: "Frankfurt",
      country: "Germany",
      continent: "Europe",
      region: "Central Europe",
      latitude: 50.0379,
      longitude: 8.5622,
      elevation_ft: 364,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1700, C: 260, F: 70 },
      slot_cost_usd: 3000,
      landing_fee_usd: 3700,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.10,
      slot_capacity: 350,
      aircraft_limit: "Heavy",
      notes: "Lufthansa’s main base with strong intercontinental connections."
    },
    {
      icao: "LIRF",
      iata: "FCO",
      city: "Rome",
      country: "Italy",
      continent: "Europe",
      region: "Southern Europe",
      latitude: 41.804,
      longitude: 12.250,
      elevation_ft: 13,
      runway_m: 3900,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1300, C: 180, F: 50 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2900,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 280,
      aircraft_limit: "Heavy",
      notes: "Main gateway for Italy, operated by ITA Airways."
    },
    {
      icao: "EHAM",
      iata: "AMS",
      city: "Amsterdam",
      country: "Netherlands",
      continent: "Europe",
      region: "Western Europe",
      latitude: 52.3086,
      longitude: 4.7639,
      elevation_ft: -11,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 240, F: 60 },
      slot_cost_usd: 2700,
      landing_fee_usd: 3100,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.08,
      slot_capacity: 320,
      aircraft_limit: "Heavy",
      notes: "Hub for KLM and SkyTeam network."
    },
    {
      icao: "ESSA",
      iata: "ARN",
      city: "Stockholm",
      country: "Sweden",
      continent: "Europe",
      region: "Northern Europe",
      latitude: 59.6498,
      longitude: 17.9238,
      elevation_ft: 137,
      runway_m: 3300,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 800, C: 90, F: 20 },
      slot_cost_usd: 1800,
      landing_fee_usd: 2100,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 0.95,
      slot_capacity: 180,
      aircraft_limit: "Medium",
      notes: "Scandinavian Airlines primary base."
    },
    {
      icao: "LOWW",
      iata: "VIE",
      city: "Vienna",
      country: "Austria",
      continent: "Europe",
      region: "Central Europe",
      latitude: 48.1103,
      longitude: 16.5697,
      elevation_ft: 600,
      runway_m: 3600,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 950, C: 110, F: 25 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2400,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.0,
      slot_capacity: 200,
      aircraft_limit: "Heavy",
      notes: "Central European connector operated by Austrian Airlines."
    },
    {
      icao: "EKCH",
      iata: "CPH",
      city: "Copenhagen",
      country: "Denmark",
      continent: "Europe",
      region: "Northern Europe",
      latitude: 55.618,
      longitude: 12.656,
      elevation_ft: 17,
      runway_m: 3600,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 900, C: 120, F: 30 },
      slot_cost_usd: 1900,
      landing_fee_usd: 2200,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.0,
      slot_capacity: 220,
      aircraft_limit: "Medium",
      notes: "Nordic hub with extensive regional operations."
    },
    {
      icao: "LEBL",
      iata: "BCN",
      city: "Barcelona",
      country: "Spain",
      continent: "Europe",
      region: "Southern Europe",
      latitude: 41.297,
      longitude: 2.078,
      elevation_ft: 12,
      runway_m: 3350,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1150, C: 140, F: 25 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2400,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Second largest airport in Spain, operated by Vueling and Iberia."
    },
    {
      icao: "LSZH",
      iata: "ZRH",
      city: "Zurich",
      country: "Switzerland",
      continent: "Europe",
      region: "Central Europe",
      latitude: 47.4647,
      longitude: 8.5492,
      elevation_ft: 1416,
      runway_m: 3700,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1400, C: 220, F: 40 },
      slot_cost_usd: 3200,
      landing_fee_usd: 3600,
      fuel_usd_gal: 3.5,
      ticket_fee_percent: 0.07,
      pax_growth_factor: 1.05,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Swiss hub with strong premium traffic."
    },
    {
      icao: "EDDM",
      iata: "MUC",
      city: "Munich",
      country: "Germany",
      continent: "Europe",
      region: "Central Europe",
      latitude: 48.3538,
      longitude: 11.7861,
      elevation_ft: 1487,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1600, C: 260, F: 55 },
      slot_cost_usd: 3400,
      landing_fee_usd: 3800,
      fuel_usd_gal: 3.6,
      ticket_fee_percent: 0.07,
      pax_growth_factor: 1.06,
      slot_capacity: 280,
      aircraft_limit: "Heavy",
      notes: "Lufthansa hub and key Star Alliance gateway."
    },
    {
      icao: "LSGG",
      iata: "GVA",
      city: "Geneva",
      country: "Switzerland",
      continent: "Europe",
      region: "Central Europe",
      latitude: 46.2381,
      longitude: 6.1090,
      elevation_ft: 1411,
      runway_m: 3900,
      open_hrs: "06–24",
      category: "International Hub",
      demand: { Y: 900, C: 130, F: 25 },
      slot_cost_usd: 2700,
      landing_fee_usd: 3000,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.07,
      pax_growth_factor: 1.04,
      slot_capacity: 200,
      aircraft_limit: "Medium",
      notes: "Leisure and business mix, strong seasonal demand."
    },
    {
      icao: "EHAM",
      iata: "AMS",
      city: "Amsterdam Schiphol",
      country: "Netherlands",
      continent: "Europe",
      region: "Western Europe",
      latitude: 52.3086,
      longitude: 4.7639,
      elevation_ft: -11,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1800, C: 280, F: 60 },
      slot_cost_usd: 3600,
      landing_fee_usd: 4000,
      fuel_usd_gal: 3.6,
      ticket_fee_percent: 0.08,
      pax_growth_factor: 1.05,
      slot_capacity: 320,
      aircraft_limit: "Heavy",
      notes: "KLM mega hub with very high connecting traffic."
    },
    {
      icao: "EKCH",
      iata: "CPH",
      city: "Copenhagen",
      country: "Denmark",
      continent: "Europe",
      region: "Nordic",
      latitude: 55.6181,
      longitude: 12.6561,
      elevation_ft: 17,
      runway_m: 3600,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 900, C: 140, F: 30 },
      slot_cost_usd: 2600,
      landing_fee_usd: 3000,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.07,
      pax_growth_factor: 1.04,
      slot_capacity: 200,
      aircraft_limit: "Heavy",
      notes: "SAS hub and key Nordic gateway."
    },
    {
      icao: "ENGM",
      iata: "OSL",
      city: "Oslo Gardermoen",
      country: "Norway",
      continent: "Europe",
      region: "Nordic",
      latitude: 60.1939,
      longitude: 11.1004,
      elevation_ft: 681,
      runway_m: 3600,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 750, C: 90, F: 15 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2600,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.03,
      slot_capacity: 160,
      aircraft_limit: "Medium",
      notes: "Scandinavian market with high domestic traffic."
    },
    {
      icao: "EKYT",
      iata: "AAL",
      city: "Aalborg",
      country: "Denmark",
      continent: "Europe",
      region: "Nordic",
      latitude: 57.0928,
      longitude: 9.8492,
      elevation_ft: 10,
      runway_m: 2650,
      open_hrs: "06–23",
      category: "Regional",
      demand: { Y: 220, C: 20, F: 0 },
      slot_cost_usd: 700,
      landing_fee_usd: 900,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.02,
      slot_capacity: 48,
      aircraft_limit: "Medium",
      notes: "Regional Scandinavian airport with leisure routes."
    },
    {
      icao: "LIMC",
      iata: "MXP",
      city: "Milan Malpensa",
      country: "Italy",
      continent: "Europe",
      region: "Southern Europe",
      latitude: 45.6306,
      longitude: 8.7281,
      elevation_ft: 768,
      runway_m: 3920,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1400, C: 190, F: 35 },
      slot_cost_usd: 3000,
      landing_fee_usd: 3400,
      fuel_usd_gal: 3.5,
      ticket_fee_percent: 0.07,
      pax_growth_factor: 1.05,
      slot_capacity: 240,
      aircraft_limit: "Heavy",
      notes: "Main international airport for northern Italy."
    },
    {
      icao: "LIRN",
      iata: "NAP",
      city: "Naples",
      country: "Italy",
      continent: "Europe",
      region: "Southern Europe",
      latitude: 40.8860,
      longitude: 14.2908,
      elevation_ft: 294,
      runway_m: 2628,
      open_hrs: "06–23",
      category: "Tourism",
      demand: { Y: 600, C: 50, F: 5 },
      slot_cost_usd: 1300,
      landing_fee_usd: 1600,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.07,
      pax_growth_factor: 1.03,
      slot_capacity: 80,
      aircraft_limit: "Medium",
      notes: "Strong seasonal demand to European cities."
    },
    {
      icao: "LGAV",
      iata: "ATH",
      city: "Athens",
      country: "Greece",
      continent: "Europe",
      region: "Southern Europe",
      latitude: 37.9364,
      longitude: 23.9475,
      elevation_ft: 308,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1100, C: 140, F: 20 },
      slot_cost_usd: 2400,
      landing_fee_usd: 2800,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.07,
      pax_growth_factor: 1.05,
      slot_capacity: 200,
      aircraft_limit: "Heavy",
      notes: "Aegean hub with strong summer traffic."
    },
    {
      icao: "LBSF",
      iata: "SOF",
      city: "Sofia",
      country: "Bulgaria",
      continent: "Europe",
      region: "Eastern Europe",
      latitude: 42.6967,
      longitude: 23.4114,
      elevation_ft: 1742,
      runway_m: 3600,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 450, C: 40, F: 5 },
      slot_cost_usd: 1100,
      landing_fee_usd: 1400,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.04,
      slot_capacity: 80,
      aircraft_limit: "Medium",
      notes: "Low-cost and regional hub in the Balkans."
    },
    {
      icao: "LHBP",
      iata: "BUD",
      city: "Budapest",
      country: "Hungary",
      continent: "Europe",
      region: "Central Europe",
      latitude: 47.4369,
      longitude: 19.2556,
      elevation_ft: 495,
      runway_m: 3700,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 750, C: 80, F: 10 },
      slot_cost_usd: 1700,
      landing_fee_usd: 2100,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.05,
      slot_capacity: 140,
      aircraft_limit: "Medium",
      notes: "Strong LCC presence and growing tourism."
   },
{
  icao: "EIDW",
  iata: "DUB",
  city: "Dublin",
  country: "Ireland",
  continent: "Europe",
  region: "Western Europe",
  latitude: 53.4213,
  longitude: -6.2701,
  elevation_ft: 242,
  runway_m: 2637,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 1100, C: 150, F: 30 },
  slot_cost_usd: 2200,
  landing_fee_usd: 2600,
  fuel_usd_gal: 3.2,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.07,
  slot_capacity: 240,
  aircraft_limit: "Heavy",
  notes: "Main hub for Aer Lingus and Ryanair."
},
{
  icao: "LPPT",
  iata: "LIS",
  city: "Lisbon",
  country: "Portugal",
  continent: "Europe",
  region: "Southern Europe",
  latitude: 38.7813,
  longitude: -9.1359,
  elevation_ft: 374,
  runway_m: 3805,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1300, C: 180, F: 35 },
  slot_cost_usd: 2400,
  landing_fee_usd: 2800,
  fuel_usd_gal: 3.2,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.08,
  slot_capacity: 260,
  aircraft_limit: "Heavy",
  notes: "TAP Air Portugal main hub."
},
{
  icao: "EBBR",
  iata: "BRU",
  city: "Brussels",
  country: "Belgium",
  continent: "Europe",
  region: "Western Europe",
  latitude: 50.9014,
  longitude: 4.4844,
  elevation_ft: 184,
  runway_m: 3638,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 1400, C: 200, F: 40 },
  slot_cost_usd: 2500,
  landing_fee_usd: 3000,
  fuel_usd_gal: 3.3,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.07,
  slot_capacity: 260,
  aircraft_limit: "Heavy",
  notes: "Brussels Airlines and European institutions hub."
},
{
  icao: "EPWA",
  iata: "WAW",
  city: "Warsaw",
  country: "Poland",
  continent: "Europe",
  region: "Central Europe",
  latitude: 52.1657,
  longitude: 20.9671,
  elevation_ft: 362,
  runway_m: 2800,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1200, C: 140, F: 30 },
  slot_cost_usd: 2100,
  landing_fee_usd: 2500,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 240,
  aircraft_limit: "Heavy",
  notes: "LOT Polish Airlines base with growing European network."
},
{
  icao: "LDZA",
  iata: "ZAG",
  city: "Zagreb",
  country: "Croatia",
  continent: "Europe",
  region: "Balkans",
  latitude: 45.7429,
  longitude: 16.0688,
  elevation_ft: 353,
  runway_m: 3250,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 550, C: 70, F: 10 },
  slot_cost_usd: 1300,
  landing_fee_usd: 1700,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.03,
  slot_capacity: 120,
  aircraft_limit: "Medium",
  notes: "Adriatic gateway with increasing tourism."
},
{
  icao: "LCLK",
  iata: "LCA",
  city: "Larnaca",
  country: "Cyprus",
  continent: "Europe",
  region: "Mediterranean",
  latitude: 34.875,
  longitude: 33.6249,
  elevation_ft: 8,
  runway_m: 3250,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 700, C: 80, F: 10 },
  slot_cost_usd: 1600,
  landing_fee_usd: 1900,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 140,
  aircraft_limit: "Medium",
  notes: "Mediterranean tourism and charter hub."
},
{
  icao: "LFMN",
  iata: "NCE",
  city: "Nice Côte d’Azur",
  country: "France",
  continent: "Europe",
  region: "Southern Europe",
  latitude: 43.6653,
  longitude: 7.215,
  elevation_ft: 12,
  runway_m: 2960,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 850, C: 100, F: 25 },
  slot_cost_usd: 2000,
  landing_fee_usd: 2300,
  fuel_usd_gal: 3.3,
  ticket_fee_percent: 0.06,
  pax_growth_factor: 1.04,
  slot_capacity: 160,
  aircraft_limit: "Medium",
  notes: "French Riviera airport with heavy summer demand."
},
{
  icao: "LEZL",
  iata: "SVQ",
  city: "Seville",
  country: "Spain",
  continent: "Europe",
  region: "Southern Europe",
  latitude: 37.417,
  longitude: -5.893,
  elevation_ft: 112,
  runway_m: 3360,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 650, C: 70, F: 10 },
  slot_cost_usd: 1400,
  landing_fee_usd: 1700,
  fuel_usd_gal: 3.2,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 120,
  aircraft_limit: "Medium",
  notes: "Strong low-cost and tourism routes."
},
{
  icao: "EFHK",
  iata: "HEL",
  city: "Helsinki",
  country: "Finland",
  continent: "Europe",
  region: "Nordic",
  latitude: 60.3172,
  longitude: 24.9633,
  elevation_ft: 179,
  runway_m: 3500,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1100, C: 160, F: 35 },
  slot_cost_usd: 2300,
  landing_fee_usd: 2700,
  fuel_usd_gal: 3.2,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 240,
  aircraft_limit: "Heavy",
  notes: "Finnair transpolar gateway between Europe and Asia."
},
{
  icao: "ENBR",
  iata: "BGO",
  city: "Bergen",
  country: "Norway",
  continent: "Europe",
  region: "Nordic",
  latitude: 60.2934,
  longitude: 5.2181,
  elevation_ft: 170,
  runway_m: 2900,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 500, C: 60, F: 5 },
  slot_cost_usd: 1200,
  landing_fee_usd: 1500,
  fuel_usd_gal: 3.2,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 90,
  aircraft_limit: "Medium",
  notes: "SAS regional focus city and oil industry traffic."
},
{
  icao: "LROP",
  iata: "OTP",
  city: "Bucharest",
  country: "Romania",
  continent: "Europe",
  region: "Eastern Europe",
  latitude: 44.5711,
  longitude: 26.085,
  elevation_ft: 314,
  runway_m: 3500,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 750, C: 90, F: 15 },
  slot_cost_usd: 1500,
  landing_fee_usd: 1900,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.03,
  slot_capacity: 120,
  aircraft_limit: "Medium",
  notes: "TAROM hub; key Balkan connector."
},
{
  icao: "ELLX",
  iata: "LUX",
  city: "Luxembourg",
  country: "Luxembourg",
  continent: "Europe",
  region: "Western Europe",
  latitude: 49.6266,
  longitude: 6.2115,
  elevation_ft: 1234,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 400, C: 50, F: 5 },
  slot_cost_usd: 1400,
  landing_fee_usd: 1700,
  fuel_usd_gal: 3.2,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Luxair and Cargolux hub; strong cargo activity."
},
{
  icao: "LWSK",
  iata: "SKP",
  city: "Skopje",
  country: "North Macedonia",
  continent: "Europe",
  region: "Balkans",
  latitude: 41.9616,
  longitude: 21.6214,
  elevation_ft: 781,
  runway_m: 2950,
  open_hrs: "24H",
  category: "Regional",
  demand: { Y: 350, C: 40, F: 0 },
  slot_cost_usd: 1000,
  landing_fee_usd: 1300,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 80,
  aircraft_limit: "Medium",
  notes: "Emerging Balkan gateway with LCC growth."
},
{
  icao: "LWSI",
  iata: "SKG",
  city: "Thessaloniki",
  country: "Greece",
  continent: "Europe",
  region: "Southern Europe",
  latitude: 40.5197,
  longitude: 22.9709,
  elevation_ft: 23,
  runway_m: 3440,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 600, C: 60, F: 5 },
  slot_cost_usd: 1300,
  landing_fee_usd: 1600,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.03,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Aegean Airlines regional base; tourism heavy."
},
{
  icao: "LPFR",
  iata: "FAO",
  city: "Faro",
  country: "Portugal",
  continent: "Europe",
  region: "Southern Europe",
  latitude: 37.014,
  longitude: -7.9659,
  elevation_ft: 24,
  runway_m: 2490,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 500, C: 40, F: 5 },
  slot_cost_usd: 1000,
  landing_fee_usd: 1300,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 80,
  aircraft_limit: "Medium",
  notes: "Southern Portugal coastal tourism hub."
},
{
  icao: "LFMN",
  iata: "BOD",
  city: "Bordeaux",
  country: "France",
  continent: "Europe",
  region: "Western Europe",
  latitude: 44.8283,
  longitude: -0.7156,
  elevation_ft: 162,
  runway_m: 3100,
  open_hrs: "24H",
  category: "Regional",
  demand: { Y: 480, C: 50, F: 5 },
  slot_cost_usd: 1100,
  landing_fee_usd: 1400,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 80,
  aircraft_limit: "Medium",
  notes: "Wine region tourism and low-cost hub."
},
{
  icao: "EGPH",
  iata: "EDI",
  city: "Edinburgh",
  country: "United Kingdom",
  continent: "Europe",
  region: "Northern Europe",
  latitude: 55.95,
  longitude: -3.372,
  elevation_ft: 136,
  runway_m: 2560,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 850, C: 90, F: 15 },
  slot_cost_usd: 1800,
  landing_fee_usd: 2100,
  fuel_usd_gal: 3.3,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 140,
  aircraft_limit: "Medium",
  notes: "Strong leisure and business traffic; major Scottish hub."
},
{
  icao: "EGCC",
  iata: "MAN",
  city: "Manchester",
  country: "United Kingdom",
  continent: "Europe",
  region: "Northern Europe",
  latitude: 53.365,
  longitude: -2.272,
  elevation_ft: 257,
  runway_m: 3048,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 1200, C: 150, F: 30 },
  slot_cost_usd: 2300,
  landing_fee_usd: 2700,
  fuel_usd_gal: 3.3,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 240,
  aircraft_limit: "Heavy",
  notes: "Largest regional hub in northern UK."
},
{
  icao: "EDDH",
  iata: "HAM",
  city: "Hamburg",
  country: "Germany",
  continent: "Europe",
  region: "Central Europe",
  latitude: 53.630,
  longitude: 9.988,
  elevation_ft: 53,
  runway_m: 3666,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 950, C: 110, F: 20 },
  slot_cost_usd: 2100,
  landing_fee_usd: 2500,
  fuel_usd_gal: 3.3,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 200,
  aircraft_limit: "Medium",
  notes: "Lufthansa and Eurowings regional base."
},
{
  icao: "EFRO",
  iata: "RVN",
  city: "Rovaniemi",
  country: "Finland",
  continent: "Europe",
  region: "Nordic",
  latitude: 66.5648,
  longitude: 25.8304,
  elevation_ft: 642,
  runway_m: 3000,
  open_hrs: "06–22",
  category: "Tourism",
  demand: { Y: 300, C: 30, F: 0 },
  slot_cost_usd: 900,
  landing_fee_usd: 1200,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.01,
  slot_capacity: 60,
  aircraft_limit: "Medium",
  notes: "Lapland winter tourism airport; heavy seasonal traffic."
},
{
  icao: "ESSB",
  iata: "BMA",
  city: "Stockholm Bromma",
  country: "Sweden",
  continent: "Europe",
  region: "Nordic",
  latitude: 59.3544,
  longitude: 17.9415,
  elevation_ft: 47,
  runway_m: 1668,
  open_hrs: "06–22",
  category: "Domestic",
  demand: { Y: 400, C: 30, F: 0 },
  slot_cost_usd: 900,
  landing_fee_usd: 1100,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.01,
  slot_capacity: 60,
  aircraft_limit: "Small",
  notes: "Stockholm’s city airport; regional turboprop operations."
},
{
  icao: "EVRA",
  iata: "RIX",
  city: "Riga",
  country: "Latvia",
  continent: "Europe",
  region: "Baltic",
  latitude: 56.9236,
  longitude: 23.9711,
  elevation_ft: 33,
  runway_m: 3200,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 800, C: 80, F: 10 },
  slot_cost_usd: 1700,
  landing_fee_usd: 2000,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 160,
  aircraft_limit: "Medium",
  notes: "AirBaltic main hub for Northern Europe."
},
{
  icao: "EYVI",
  iata: "VNO",
  city: "Vilnius",
  country: "Lithuania",
  continent: "Europe",
  region: "Baltic",
  latitude: 54.6341,
  longitude: 25.2858,
  elevation_ft: 646,
  runway_m: 2515,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 500, C: 40, F: 5 },
  slot_cost_usd: 1200,
  landing_fee_usd: 1500,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Lithuania’s main airport with strong LCC traffic."
},
{
  icao: "EETN",
  iata: "TLL",
  city: "Tallinn",
  country: "Estonia",
  continent: "Europe",
  region: "Baltic",
  latitude: 59.4133,
  longitude: 24.8328,
  elevation_ft: 131,
  runway_m: 3480,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 480, C: 40, F: 5 },
  slot_cost_usd: 1200,
  landing_fee_usd: 1500,
  fuel_usd_gal: 3.2,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Tallinn airport serves Baltic and Nordic connections."
},
{
  icao: "UMMS",
  iata: "MSQ",
  city: "Minsk",
  country: "Belarus",
  continent: "Europe",
  region: "Eastern Europe",
  latitude: 53.8825,
  longitude: 28.0307,
  elevation_ft: 670,
  runway_m: 3640,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 450, C: 50, F: 10 },
  slot_cost_usd: 1300,
  landing_fee_usd: 1600,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Former Belavia hub; currently limited international traffic."
},
{
  icao: "UKBB",
  iata: "KBP",
  city: "Kyiv Boryspil",
  country: "Ukraine",
  continent: "Europe",
  region: "Eastern Europe",
  latitude: 50.345,
  longitude: 30.8947,
  elevation_ft: 427,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1000, C: 120, F: 25 },
  slot_cost_usd: 1800,
  landing_fee_usd: 2200,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.03,
  slot_capacity: 180,
  aircraft_limit: "Heavy",
  notes: "Ukraine International hub; operations subject to restoration."
},
{
  icao: "UKLL",
  iata: "LWO",
  city: "Lviv",
  country: "Ukraine",
  continent: "Europe",
  region: "Eastern Europe",
  latitude: 49.812,
  longitude: 23.956,
  elevation_ft: 1071,
  runway_m: 3305,
  open_hrs: "24H",
  category: "Regional",
  demand: { Y: 400, C: 30, F: 5 },
  slot_cost_usd: 1100,
  landing_fee_usd: 1400,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 80,
  aircraft_limit: "Medium",
  notes: "Western Ukraine airport; tourism and charter routes."
},
{
  icao: "LZIB",
  iata: "BTS",
  city: "Bratislava",
  country: "Slovakia",
  continent: "Europe",
  region: "Central Europe",
  latitude: 48.17,
  longitude: 17.212,
  elevation_ft: 436,
  runway_m: 3190,
  open_hrs: "24H",
  category: "Regional",
  demand: { Y: 350, C: 40, F: 5 },
  slot_cost_usd: 1000,
  landing_fee_usd: 1300,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 80,
  aircraft_limit: "Medium",
  notes: "Low-cost and leisure traffic; proximity to Vienna."
},
{
  icao: "LBSF",
  iata: "VAR",
  city: "Varna",
  country: "Bulgaria",
  continent: "Europe",
  region: "Eastern Europe",
  latitude: 43.232,
  longitude: 27.825,
  elevation_ft: 230,
  runway_m: 2500,
  open_hrs: "06–23",
  category: "Tourism",
  demand: { Y: 400, C: 30, F: 0 },
  slot_cost_usd: 900,
  landing_fee_usd: 1200,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 70,
  aircraft_limit: "Medium",
  notes: "Black Sea resort traffic; seasonal charter base."
},
{
  icao: "LRCL",
  iata: "CLJ",
  city: "Cluj-Napoca",
  country: "Romania",
  continent: "Europe",
  region: "Eastern Europe",
  latitude: 46.785,
  longitude: 23.686,
  elevation_ft: 1036,
  runway_m: 2100,
  open_hrs: "06–22",
  category: "Regional",
  demand: { Y: 300, C: 30, F: 0 },
  slot_cost_usd: 800,
  landing_fee_usd: 1100,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.01,
  slot_capacity: 60,
  aircraft_limit: "Medium",
  notes: "LCC hub for central Romania."
},
{
  icao: "LHPR",
  iata: "GYR",
  city: "Győr-Pér",
  country: "Hungary",
  continent: "Europe",
  region: "Central Europe",
  latitude: 47.627,
  longitude: 17.81,
  elevation_ft: 424,
  runway_m: 2030,
  open_hrs: "06–22",
  category: "Regional",
  demand: { Y: 200, C: 20, F: 0 },
  slot_cost_usd: 700,
  landing_fee_usd: 1000,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.01,
  slot_capacity: 40,
  aircraft_limit: "Medium",
  notes: "Industrial charter and cargo support airport."
},
{
  icao: "LUCL",
  iata: "KIV",
  city: "Chișinău",
  country: "Moldova",
  continent: "Europe",
  region: "Eastern Europe",
  latitude: 46.927,
  longitude: 28.931,
  elevation_ft: 397,
  runway_m: 3590,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 400, C: 40, F: 5 },
  slot_cost_usd: 1100,
  landing_fee_usd: 1500,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 80,
  aircraft_limit: "Medium",
  notes: "Moldova’s primary gateway."
},
{
  icao: "LDSP",
  iata: "SPU",
  city: "Split",
  country: "Croatia",
  continent: "Europe",
  region: "Adriatic",
  latitude: 43.5389,
  longitude: 16.297,
  elevation_ft: 78,
  runway_m: 2550,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 500, C: 50, F: 5 },
  slot_cost_usd: 1300,
  landing_fee_usd: 1600,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.03,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Adriatic coastal airport; high summer demand."
},
{
  icao: "LDDU",
  iata: "DBV",
  city: "Dubrovnik",
  country: "Croatia",
  continent: "Europe",
  region: "Adriatic",
  latitude: 42.561,
  longitude: 18.268,
  elevation_ft: 527,
  runway_m: 3300,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 550, C: 60, F: 5 },
  slot_cost_usd: 1400,
  landing_fee_usd: 1700,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.03,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Major Adriatic tourism gateway."
},
{
  icao: "LTFM",
  iata: "IST",
  city: "Istanbul",
  country: "Türkiye",
  continent: "Europe",
  region: "Southeastern Europe",
  latitude: 41.275,
  longitude: 28.751,
  elevation_ft: 325,
  runway_m: 4100,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 2200, C: 300, F: 70 },
  slot_cost_usd: 3400,
  landing_fee_usd: 3800,
  fuel_usd_gal: 3.3,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.12,
  slot_capacity: 400,
  aircraft_limit: "Heavy",
  notes: "Turkish Airlines’ main intercontinental hub."
}
  ], // end Europe
  /* =============================================================
     🌏 ASIA
     ============================================================= */
  Asia: [
    {
      icao: "VHHH",
      iata: "HKG",
      city: "Hong Kong",
      country: "China (SAR)",
      continent: "Asia",
      region: "East Asia",
      latitude: 22.308,
      longitude: 113.9185,
      elevation_ft: 28,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1900, C: 260, F: 70 },
      slot_cost_usd: 3100,
      landing_fee_usd: 3500,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.20,
      slot_capacity: 380,
      aircraft_limit: "Heavy",
      notes: "Major Asian gateway and Cathay Pacific hub."
    },
    {
      icao: "RJTT",
      iata: "HND",
      city: "Tokyo Haneda",
      country: "Japan",
      continent: "Asia",
      region: "East Asia",
      latitude: 35.5523,
      longitude: 139.7798,
      elevation_ft: 21,
      runway_m: 3360,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2000, C: 320, F: 80 },
      slot_cost_usd: 3300,
      landing_fee_usd: 3700,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.25,
      slot_capacity: 400,
      aircraft_limit: "Heavy",
      notes: "Main Tokyo hub with domestic and international demand."
    },
    {
      icao: "RKSI",
      iata: "ICN",
      city: "Seoul Incheon",
      country: "South Korea",
      continent: "Asia",
      region: "East Asia",
      latitude: 37.4691,
      longitude: 126.4505,
      elevation_ft: 23,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1700, C: 230, F: 50 },
      slot_cost_usd: 2800,
      landing_fee_usd: 3200,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.10,
      slot_capacity: 340,
      aircraft_limit: "Heavy",
      notes: "Korean Air and Asiana hub with strong long-haul demand."
    },
    {
      icao: "ZBAA",
      iata: "PEK",
      city: "Beijing Capital",
      country: "China",
      continent: "Asia",
      region: "East Asia",
      latitude: 40.08,
      longitude: 116.5846,
      elevation_ft: 116,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2100, C: 290, F: 60 },
      slot_cost_usd: 3000,
      landing_fee_usd: 3400,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.15,
      slot_capacity: 360,
      aircraft_limit: "Heavy",
      notes: "Main hub for Air China and international gateway to Beijing."
    },
    {
      icao: "ZSPD",
      iata: "PVG",
      city: "Shanghai Pudong",
      country: "China",
      continent: "Asia",
      region: "East Asia",
      latitude: 31.1434,
      longitude: 121.8052,
      elevation_ft: 13,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2000, C: 270, F: 70 },
      slot_cost_usd: 3100,
      landing_fee_usd: 3600,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.12,
      slot_capacity: 370,
      aircraft_limit: "Heavy",
      notes: "China Eastern and international long-haul hub."
    },
    {
      icao: "VTBS",
      iata: "BKK",
      city: "Bangkok Suvarnabhumi",
      country: "Thailand",
      continent: "Asia",
      region: "Southeast Asia",
      latitude: 13.690,
      longitude: 100.750,
      elevation_ft: 5,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1400, C: 160, F: 30 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2700,
      fuel_usd_gal: 2.9,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 280,
      aircraft_limit: "Heavy",
      notes: "Main gateway for Southeast Asia tourism and Thai Airways base."
    },
    {
      icao: "WMKK",
      iata: "KUL",
      city: "Kuala Lumpur",
      country: "Malaysia",
      continent: "Asia",
      region: "Southeast Asia",
      latitude: 2.7456,
      longitude: 101.709,
      elevation_ft: 70,
      runway_m: 4100,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1200, C: 140, F: 25 },
      slot_cost_usd: 2100,
      landing_fee_usd: 2500,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.0,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Malaysia Airlines and AirAsia hub."
    },
    {
      icao: "WSSS",
      iata: "SIN",
      city: "Singapore",
      country: "Singapore",
      continent: "Asia",
      region: "Southeast Asia",
      latitude: 1.3644,
      longitude: 103.9915,
      elevation_ft: 22,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1700, C: 240, F: 50 },
      slot_cost_usd: 2600,
      landing_fee_usd: 3000,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.08,
      slot_capacity: 320,
      aircraft_limit: "Heavy",
      notes: "Flagship airport for Singapore Airlines."
    },
    {
      icao: "VIDP",
      iata: "DEL",
      city: "Delhi Indira Gandhi",
      country: "India",
      continent: "Asia",
      region: "South Asia",
      latitude: 28.5562,
      longitude: 77.1000,
      elevation_ft: 777,
      runway_m: 4430,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 180, F: 40 },
      slot_cost_usd: 2400,
      landing_fee_usd: 2800,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.1,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "Main Indian international gateway."
    },
    {
      icao: "UCFM",
      iata: "FRU",
      city: "Bishkek",
      country: "Kyrgyzstan",
      continent: "Asia",
      region: "Central Asia",
      latitude: 43.0613,
      longitude: 74.4776,
      elevation_ft: 2058,
      runway_m: 4200,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 250, C: 30, F: 5 },
      slot_cost_usd: 600,
      landing_fee_usd: 850,
      fuel_usd_gal: 2.7,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.0,
      slot_capacity: 80,
      aircraft_limit: "Heavy",
      notes: "Central Asian airport with growing regional demand."
    },
    {
  icao: "RJAA",
  iata: "NRT",
  city: "Tokyo Narita",
  country: "Japan",
  continent: "Asia",
  region: "East Asia",
  latitude: 35.765,
  longitude: 140.386,
  elevation_ft: 141,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1800, C: 280, F: 70 },
  slot_cost_usd: 3100,
  landing_fee_usd: 3500,
  fuel_usd_gal: 3.2,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.10,
  slot_capacity: 380,
  aircraft_limit: "Heavy",
  notes: "Tokyo’s main international long-haul airport."
},
{
  icao: "RJBB",
  iata: "KIX",
  city: "Osaka Kansai",
  country: "Japan",
  continent: "Asia",
  region: "East Asia",
  latitude: 34.434,
  longitude: 135.232,
  elevation_ft: 17,
  runway_m: 3500,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 1300, C: 160, F: 40 },
  slot_cost_usd: 2400,
  landing_fee_usd: 2800,
  fuel_usd_gal: 3.2,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 260,
  aircraft_limit: "Heavy",
  notes: "Western Japan international hub; All Nippon & LCCs."
},
{
  icao: "RJCC",
  iata: "CTS",
  city: "Sapporo New Chitose",
  country: "Japan",
  continent: "Asia",
  region: "East Asia",
  latitude: 42.775,
  longitude: 141.692,
  elevation_ft: 70,
  runway_m: 3000,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 1000, C: 100, F: 20 },
  slot_cost_usd: 2000,
  landing_fee_usd: 2300,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 200,
  aircraft_limit: "Heavy",
  notes: "Main airport for Hokkaido; domestic tourism hub."
},
{
  icao: "RPLL",
  iata: "MNL",
  city: "Manila Ninoy Aquino",
  country: "Philippines",
  continent: "Asia",
  region: "Southeast Asia",
  latitude: 14.509,
  longitude: 121.013,
  elevation_ft: 75,
  runway_m: 3700,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1500, C: 150, F: 30 },
  slot_cost_usd: 2400,
  landing_fee_usd: 2700,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.08,
  slot_capacity: 260,
  aircraft_limit: "Heavy",
  notes: "Philippine Airlines and Cebu Pacific hub."
},
{
  icao: "RPVM",
  iata: "CEB",
  city: "Cebu Mactan",
  country: "Philippines",
  continent: "Asia",
  region: "Southeast Asia",
  latitude: 10.307,
  longitude: 123.979,
  elevation_ft: 31,
  runway_m: 3300,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 900, C: 80, F: 10 },
  slot_cost_usd: 1600,
  landing_fee_usd: 1900,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 160,
  aircraft_limit: "Medium",
  notes: "Secondary hub in the Philippines; major leisure routes."
},
{
  icao: "ZPPP",
  iata: "KMG",
  city: "Kunming",
  country: "China",
  continent: "Asia",
  region: "Southwest China",
  latitude: 25.102,
  longitude: 102.929,
  elevation_ft: 6900,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 1100, C: 120, F: 25 },
  slot_cost_usd: 2000,
  landing_fee_usd: 2300,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 220,
  aircraft_limit: "Heavy",
  notes: "Southwest China connector with high-altitude operations."
},
{
  icao: "ZGGG",
  iata: "CAN",
  city: "Guangzhou Baiyun",
  country: "China",
  continent: "Asia",
  region: "South China",
  latitude: 23.392,
  longitude: 113.299,
  elevation_ft: 50,
  runway_m: 3800,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 2000, C: 260, F: 50 },
  slot_cost_usd: 3000,
  landing_fee_usd: 3400,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.12,
  slot_capacity: 340,
  aircraft_limit: "Heavy",
  notes: "China Southern main base and one of China’s busiest hubs."
},
{
  icao: "ZUCK",
  iata: "CKG",
  city: "Chongqing Jiangbei",
  country: "China",
  continent: "Asia",
  region: "Central China",
  latitude: 29.719,
  longitude: 106.642,
  elevation_ft: 1400,
  runway_m: 3600,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 1400, C: 140, F: 25 },
  slot_cost_usd: 2300,
  landing_fee_usd: 2600,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.07,
  slot_capacity: 240,
  aircraft_limit: "Heavy",
  notes: "Large domestic and cargo hub in western China."
},
{
  icao: "ZLXY",
  iata: "XIY",
  city: "Xi’an Xianyang",
  country: "China",
  continent: "Asia",
  region: "Central China",
  latitude: 34.447,
  longitude: 108.752,
  elevation_ft: 1572,
  runway_m: 3800,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 1200, C: 110, F: 20 },
  slot_cost_usd: 2200,
  landing_fee_usd: 2500,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 200,
  aircraft_limit: "Heavy",
  notes: "Large historical and tourism hub of northwest China."
},
{
  icao: "VABB",
  iata: "BOM",
  city: "Mumbai",
  country: "India",
  continent: "Asia",
  region: "South Asia",
  latitude: 19.0896,
  longitude: 72.8656,
  elevation_ft: 39,
  runway_m: 3660,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1800, C: 200, F: 40 },
  slot_cost_usd: 2600,
  landing_fee_usd: 3000,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.09,
  slot_capacity: 320,
  aircraft_limit: "Heavy",
  notes: "India’s busiest airport; Vistara and Air India base."
},
{
  icao: "VOBL",
  iata: "BLR",
  city: "Bengaluru",
  country: "India",
  continent: "Asia",
  region: "South Asia",
  latitude: 13.1986,
  longitude: 77.7066,
  elevation_ft: 3000,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 1300, C: 130, F: 20 },
  slot_cost_usd: 2300,
  landing_fee_usd: 2600,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.07,
  slot_capacity: 260,
  aircraft_limit: "Heavy",
  notes: "Southern India technology hub and major gateway."
},
{
  icao: "VOTV",
  iata: "TRV",
  city: "Trivandrum",
  country: "India",
  continent: "Asia",
  region: "South India",
  latitude: 8.482,
  longitude: 76.920,
  elevation_ft: 15,
  runway_m: 3397,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 600, C: 60, F: 10 },
  slot_cost_usd: 1300,
  landing_fee_usd: 1600,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Gateway to Kerala and Gulf connections."
},
{
  icao: "VGHS",
  iata: "DAC",
  city: "Dhaka",
  country: "Bangladesh",
  continent: "Asia",
  region: "South Asia",
  latitude: 23.842,
  longitude: 90.399,
  elevation_ft: 30,
  runway_m: 3200,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 1000, C: 90, F: 15 },
  slot_cost_usd: 1900,
  landing_fee_usd: 2200,
  fuel_usd_gal: 2.9,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 160,
  aircraft_limit: "Medium",
  notes: "Biman Bangladesh hub with South Asia and Gulf traffic."
},
{
  icao: "VECC",
  iata: "CCU",
  city: "Kolkata",
  country: "India",
  continent: "Asia",
  region: "South Asia",
  latitude: 22.654,
  longitude: 88.447,
  elevation_ft: 16,
  runway_m: 3610,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 1000, C: 90, F: 15 },
  slot_cost_usd: 2000,
  landing_fee_usd: 2400,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 160,
  aircraft_limit: "Medium",
  notes: "Eastern India hub for domestic and Southeast Asia routes."
},
{
  icao: "VTCC",
  iata: "CNX",
  city: "Chiang Mai",
  country: "Thailand",
  continent: "Asia",
  region: "Southeast Asia",
  latitude: 18.767,
  longitude: 98.963,
  elevation_ft: 1031,
  runway_m: 3100,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 700, C: 60, F: 5 },
  slot_cost_usd: 1400,
  landing_fee_usd: 1700,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 120,
  aircraft_limit: "Medium",
  notes: "Thailand’s northern tourism center."
},
{
  icao: "WIII",
  iata: "CGK",
  city: "Jakarta Soekarno-Hatta",
  country: "Indonesia",
  continent: "Asia",
  region: "Southeast Asia",
  latitude: -6.125,
  longitude: 106.655,
  elevation_ft: 34,
  runway_m: 3660,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1900, C: 180, F: 30 },
  slot_cost_usd: 2500,
  landing_fee_usd: 2900,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.10,
  slot_capacity: 300,
  aircraft_limit: "Heavy",
  notes: "Garuda Indonesia and Lion Air hub."
},
{
  icao: "WADD",
  iata: "DPS",
  city: "Bali Denpasar",
  country: "Indonesia",
  continent: "Asia",
  region: "Southeast Asia",
  latitude: -8.748,
  longitude: 115.167,
  elevation_ft: 14,
  runway_m: 3000,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 1200, C: 100, F: 20 },
  slot_cost_usd: 1900,
  landing_fee_usd: 2200,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 160,
  aircraft_limit: "Heavy",
  notes: "One of Asia’s busiest leisure destinations."
},
{
  icao: "WARR",
  iata: "SUB",
  city: "Surabaya",
  country: "Indonesia",
  continent: "Asia",
  region: "Southeast Asia",
  latitude: -7.379,
  longitude: 112.787,
  elevation_ft: 9,
  runway_m: 3000,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 900, C: 90, F: 15 },
  slot_cost_usd: 1600,
  landing_fee_usd: 1900,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 140,
  aircraft_limit: "Medium",
  notes: "Eastern Indonesia domestic hub."
},
{
  icao: "UAAA",
  iata: "ALA",
  city: "Almaty",
  country: "Kazakhstan",
  continent: "Asia",
  region: "Central Asia",
  latitude: 43.353,
  longitude: 77.041,
  elevation_ft: 2234,
  runway_m: 4400,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 800, C: 90, F: 15 },
  slot_cost_usd: 1800,
  landing_fee_usd: 2100,
  fuel_usd_gal: 2.8,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 160,
  aircraft_limit: "Heavy",
  notes: "Kazakhstan’s main international airport."
},
{
  icao: "UTTT",
  iata: "TAS",
  city: "Tashkent",
  country: "Uzbekistan",
  continent: "Asia",
  region: "Central Asia",
  latitude: 41.257,
  longitude: 69.282,
  elevation_ft: 1415,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 750, C: 70, F: 10 },
  slot_cost_usd: 1600,
  landing_fee_usd: 1900,
  fuel_usd_gal: 2.8,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 140,
  aircraft_limit: "Medium",
  notes: "Uzbekistan Airways base and Central Asian connector."
},
{
  icao: "UATT",
  iata: "AKX",
  city: "Aktobe",
  country: "Kazakhstan",
  continent: "Asia",
  region: "Central Asia",
  latitude: 50.25,
  longitude: 57.2,
  elevation_ft: 738,
  runway_m: 3100,
  open_hrs: "24H",
  category: "Regional",
  demand: { Y: 400, C: 30, F: 0 },
  slot_cost_usd: 1000,
  landing_fee_usd: 1300,
  fuel_usd_gal: 2.8,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 80,
  aircraft_limit: "Medium",
  notes: "Western Kazakhstan regional airport."
},
{
  icao: "UTDD",
  iata: "DYU",
  city: "Dushanbe",
  country: "Tajikistan",
  continent: "Asia",
  region: "Central Asia",
  latitude: 38.543,
  longitude: 68.825,
  elevation_ft: 2575,
  runway_m: 3200,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 500, C: 50, F: 5 },
  slot_cost_usd: 1200,
  landing_fee_usd: 1500,
  fuel_usd_gal: 2.9,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.03,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Mountainous approach; Central Asia connectivity."
},
{
  icao: "OIII",
  iata: "IKA",
  city: "Tehran Imam Khomeini",
  country: "Iran",
  continent: "Asia",
  region: "Middle East",
  latitude: 35.416,
  longitude: 51.152,
  elevation_ft: 3260,
  runway_m: 4200,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1200, C: 130, F: 25 },
  slot_cost_usd: 2200,
  landing_fee_usd: 2600,
  fuel_usd_gal: 2.9,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.07,
  slot_capacity: 240,
  aircraft_limit: "Heavy",
  notes: "Main Iranian gateway to Asia and Europe."
},
{
  icao: "OMDB",
  iata: "DXB",
  city: "Dubai International",
  country: "UAE",
  continent: "Asia",
  region: "Middle East",
  latitude: 25.252,
  longitude: 55.364,
  elevation_ft: 62,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 2400, C: 300, F: 80 },
  slot_cost_usd: 3500,
  landing_fee_usd: 3900,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.15,
  slot_capacity: 400,
  aircraft_limit: "Heavy",
  notes: "Emirates mega hub for long-haul operations."
},
{
  icao: "OBBI",
  iata: "BAH",
  city: "Bahrain",
  country: "Bahrain",
  continent: "Asia",
  region: "Middle East",
  latitude: 26.27,
  longitude: 50.633,
  elevation_ft: 6,
  runway_m: 3800,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 900, C: 100, F: 20 },
  slot_cost_usd: 2000,
  landing_fee_usd: 2300,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 180,
  aircraft_limit: "Heavy",
  notes: "Gulf Air hub with strong Middle East connectivity."
},
{
  icao: "OOMS",
  iata: "MCT",
  city: "Muscat",
  country: "Oman",
  continent: "Asia",
  region: "Middle East",
  latitude: 23.593,
  longitude: 58.284,
  elevation_ft: 15,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1000, C: 110, F: 25 },
  slot_cost_usd: 2100,
  landing_fee_usd: 2400,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 200,
  aircraft_limit: "Heavy",
  notes: "Oman Air base; gateway between Asia and Africa."
},
{
  icao: "VTSP",
  iata: "HKT",
  city: "Phuket",
  country: "Thailand",
  continent: "Asia",
  region: "Southeast Asia",
  latitude: 8.113,
  longitude: 98.317,
  elevation_ft: 82,
  runway_m: 3000,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 1100, C: 100, F: 20 },
  slot_cost_usd: 1700,
  landing_fee_usd: 2000,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 160,
  aircraft_limit: "Medium",
  notes: "Thailand’s top leisure airport; international charters."
},
{
  icao: "VVNB",
  iata: "HAN",
  city: "Hanoi Noi Bai",
  country: "Vietnam",
  continent: "Asia",
  region: "Southeast Asia",
  latitude: 21.221,
  longitude: 105.806,
  elevation_ft: 39,
  runway_m: 3800,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 1300, C: 120, F: 20 },
  slot_cost_usd: 2100,
  landing_fee_usd: 2500,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.07,
  slot_capacity: 220,
  aircraft_limit: "Heavy",
  notes: "Vietnam Airlines’ northern hub."
},
{
  icao: "VVTS",
  iata: "SGN",
  city: "Ho Chi Minh City",
  country: "Vietnam",
  continent: "Asia",
  region: "Southeast Asia",
  latitude: 10.818,
  longitude: 106.652,
  elevation_ft: 33,
  runway_m: 3800,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1600, C: 150, F: 25 },
  slot_cost_usd: 2300,
  landing_fee_usd: 2700,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.08,
  slot_capacity: 240,
  aircraft_limit: "Heavy",
  notes: "Southern Vietnam gateway; large domestic network."
},
{
  icao: "WMKK",
  iata: "KUL",
  city: "Kuala Lumpur",
  country: "Malaysia",
  continent: "Asia",
  region: "Southeast Asia",
  latitude: 2.745,
  longitude: 101.71,
  elevation_ft: 69,
  runway_m: 4124,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1900, C: 200, F: 35 },
  slot_cost_usd: 2700,
  landing_fee_usd: 3100,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.09,
  slot_capacity: 300,
  aircraft_limit: "Heavy",
  notes: "Malaysia Airlines and AirAsia dual hub."
}
  ], // end Asia
  /* =============================================================
     🌎 NORTH AMERICA
     ============================================================= */
  NorthAmerica: [
    {
      icao: "KJFK",
      iata: "JFK",
      city: "New York",
      country: "United States",
      continent: "North America",
      region: "Northeast USA",
      latitude: 40.6413,
      longitude: -73.7781,
      elevation_ft: 13,
      runway_m: 4441,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2400, C: 380, F: 100 },
      slot_cost_usd: 3800,
      landing_fee_usd: 4200,
      fuel_usd_gal: 3.5,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.20,
      slot_capacity: 420,
      aircraft_limit: "Heavy",
      notes: "Main US international gateway; major slot-controlled hub."
    },
    {
      icao: "KLAX",
      iata: "LAX",
      city: "Los Angeles",
      country: "United States",
      continent: "North America",
      region: "West Coast",
      latitude: 33.9416,
      longitude: -118.4085,
      elevation_ft: 125,
      runway_m: 3682,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2300, C: 330, F: 80 },
      slot_cost_usd: 3400,
      landing_fee_usd: 4000,
      fuel_usd_gal: 3.6,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.18,
      slot_capacity: 400,
      aircraft_limit: "Heavy",
      notes: "Massive international and domestic hub with heavy long-haul ops."
    },
    {
      icao: "KMIA",
      iata: "MIA",
      city: "Miami",
      country: "United States",
      continent: "North America",
      region: "Southeast USA",
      latitude: 25.7959,
      longitude: -80.2870,
      elevation_ft: 8,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1800, C: 260, F: 60 },
      slot_cost_usd: 2800,
      landing_fee_usd: 3200,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.10,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "American Airlines Latin American hub; large connection volume."
    },
    {
      icao: "KORD",
      iata: "ORD",
      city: "Chicago O'Hare",
      country: "United States",
      continent: "North America",
      region: "Midwest USA",
      latitude: 41.9742,
      longitude: -87.9073,
      elevation_ft: 672,
      runway_m: 3962,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2200, C: 300, F: 70 },
      slot_cost_usd: 3300,
      landing_fee_usd: 3700,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.15,
      slot_capacity: 350,
      aircraft_limit: "Heavy",
      notes: "United and American Airlines hub; strong transatlantic presence."
    },
    {
      icao: "CYYZ",
      iata: "YYZ",
      city: "Toronto Pearson",
      country: "Canada",
      continent: "North America",
      region: "Canada",
      latitude: 43.6777,
      longitude: -79.6248,
      elevation_ft: 569,
      runway_m: 3897,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 200, F: 40 },
      slot_cost_usd: 2600,
      landing_fee_usd: 3000,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.08,
      slot_capacity: 280,
      aircraft_limit: "Heavy",
      notes: "Air Canada main hub; connects North America to Europe and Asia."
    },
    {
      icao: "CYVR",
      iata: "YVR",
      city: "Vancouver",
      country: "Canada",
      continent: "North America",
      region: "Canada West",
      latitude: 49.1947,
      longitude: -123.1792,
      elevation_ft: 14,
      runway_m: 3500,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1200, C: 160, F: 30 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2600,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.05,
      slot_capacity: 220,
      aircraft_limit: "Heavy",
      notes: "Pacific gateway for Air Canada and WestJet operations."
    },
    {
      icao: "MMMX",
      iata: "MEX",
      city: "Mexico City",
      country: "Mexico",
      continent: "North America",
      region: "Mexico",
      latitude: 19.436,
      longitude: -99.072,
      elevation_ft: 7316,
      runway_m: 3960,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1600, C: 180, F: 40 },
      slot_cost_usd: 2400,
      landing_fee_usd: 2700,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.10,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "High-altitude international hub; base for Aeromexico."
    },
    {
      icao: "KSFO",
      iata: "SFO",
      city: "San Francisco",
      country: "United States",
      continent: "North America",
      region: "West Coast",
      latitude: 37.6213,
      longitude: -122.3790,
      elevation_ft: 13,
      runway_m: 3618,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1800, C: 260, F: 55 },
      slot_cost_usd: 3200,
      landing_fee_usd: 3500,
      fuel_usd_gal: 3.6,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.12,
      slot_capacity: 320,
      aircraft_limit: "Heavy",
      notes: "United Airlines hub and strong Pacific gateway."
    },
    {
      icao: "KATL",
      iata: "ATL",
      city: "Atlanta",
      country: "United States",
      continent: "North America",
      region: "Southeast USA",
      latitude: 33.6407,
      longitude: -84.4277,
      elevation_ft: 1026,
      runway_m: 3743,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2600, C: 310, F: 60 },
      slot_cost_usd: 3200,
      landing_fee_usd: 3600,
      fuel_usd_gal: 3.5,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.18,
      slot_capacity: 420,
      aircraft_limit: "Heavy",
      notes: "World’s busiest airport by movements; Delta’s global hub."
    },
    {
      icao: "KDFW",
      iata: "DFW",
      city: "Dallas/Fort Worth",
      country: "United States",
      continent: "North America",
      region: "South USA",
      latitude: 32.8998,
      longitude: -97.0403,
      elevation_ft: 607,
      runway_m: 4110,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 2100, C: 250, F: 50 },
      slot_cost_usd: 3000,
      landing_fee_usd: 3400,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.15,
      slot_capacity: 360,
      aircraft_limit: "Heavy",
      notes: "American Airlines global hub; major domestic connectivity."
    }
  ], // end North America
  /* =============================================================
     🌎 SOUTH AMERICA
     ============================================================= */
  SouthAmerica: [
    {
      icao: "SKBO",
      iata: "BOG",
      city: "Bogotá",
      country: "Colombia",
      continent: "South America",
      region: "Andean Region",
      latitude: 4.7016,
      longitude: -74.1469,
      elevation_ft: 8361,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 180, F: 35 },
      slot_cost_usd: 2100,
      landing_fee_usd: 2600,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.08,
      slot_capacity: 280,
      aircraft_limit: "Heavy",
      notes: "Avianca main hub and regional connector."
    },
    {
      icao: "SBGR",
      iata: "GRU",
      city: "São Paulo Guarulhos",
      country: "Brazil",
      continent: "South America",
      region: "Southeast Brazil",
      latitude: -23.4356,
      longitude: -46.4731,
      elevation_ft: 2459,
      runway_m: 3700,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1600, C: 220, F: 50 },
      slot_cost_usd: 2300,
      landing_fee_usd: 2700,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.10,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "LATAM Airlines and international long-haul base."
    },
    {
      icao: "SAEZ",
      iata: "EZE",
      city: "Buenos Aires Ezeiza",
      country: "Argentina",
      continent: "South America",
      region: "Southern Cone",
      latitude: -34.8222,
      longitude: -58.5358,
      elevation_ft: 67,
      runway_m: 3300,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1300, C: 150, F: 40 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2400,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Aerolineas Argentinas main gateway for intercontinental flights."
    },
    {
      icao: "SPJC",
      iata: "LIM",
      city: "Lima",
      country: "Peru",
      continent: "South America",
      region: "Pacific Coast",
      latitude: -12.0219,
      longitude: -77.1143,
      elevation_ft: 113,
      runway_m: 3507,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1200, C: 130, F: 25 },
      slot_cost_usd: 1900,
      landing_fee_usd: 2300,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 240,
      aircraft_limit: "Heavy",
      notes: "LATAM Peru hub connecting South America and North America."
    },
    {
      icao: "SCEL",
      iata: "SCL",
      city: "Santiago de Chile",
      country: "Chile",
      continent: "South America",
      region: "Southern Cone",
      latitude: -33.3929,
      longitude: -70.7858,
      elevation_ft: 1555,
      runway_m: 3830,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1400, C: 160, F: 30 },
      slot_cost_usd: 2100,
      landing_fee_usd: 2500,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.08,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "LATAM Chile hub; high reliability airport."
    },
    {
      icao: "SEQM",
      iata: "UIO",
      city: "Quito",
      country: "Ecuador",
      continent: "South America",
      region: "Andean Region",
      latitude: -0.1292,
      longitude: -78.3575,
      elevation_ft: 7841,
      runway_m: 4100,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 800, C: 90, F: 15 },
      slot_cost_usd: 1400,
      landing_fee_usd: 1800,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.03,
      slot_capacity: 160,
      aircraft_limit: "Medium",
      notes: "Modern airport at high altitude serving regional connections."
    },
    {
      icao: "SVMI",
      iata: "CCS",
      city: "Caracas",
      country: "Venezuela",
      continent: "South America",
      region: "Caribbean Coast",
      latitude: 10.6031,
      longitude: -66.9906,
      elevation_ft: 235,
      runway_m: 3500,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 700, C: 80, F: 15 },
      slot_cost_usd: 1300,
      landing_fee_usd: 1600,
      fuel_usd_gal: 2.9,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 0.95,
      slot_capacity: 140,
      aircraft_limit: "Medium",
      notes: "Former regional hub with limited but stable operations."
    },
    {
      icao: "SBBR",
      iata: "BSB",
      city: "Brasília",
      country: "Brazil",
      continent: "South America",
      region: "Central Brazil",
      latitude: -15.8697,
      longitude: -47.9208,
      elevation_ft: 3481,
      runway_m: 3300,
      open_hrs: "24H",
      category: "National Hub",
      demand: { Y: 900, C: 110, F: 20 },
      slot_cost_usd: 1700,
      landing_fee_usd: 2100,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.04,
      slot_capacity: 200,
      aircraft_limit: "Medium",
      notes: "Governmental and domestic central hub of Brazil."
    },
    {
      icao: "SBGL",
      iata: "GIG",
      city: "Rio de Janeiro",
      country: "Brazil",
      continent: "South America",
      region: "Southeast Brazil",
      latitude: -22.809,
      longitude: -43.2506,
      elevation_ft: 28,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1200, C: 150, F: 35 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2400,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.06,
      slot_capacity: 240,
      aircraft_limit: "Heavy",
      notes: "Tourism-heavy airport; secondary hub to São Paulo."
    }
  ], // end South America
  /* =============================================================
     🌍 AFRICA
     ============================================================= */
  Africa: [
    {
      icao: "FAOR",
      iata: "JNB",
      city: "Johannesburg O.R. Tambo",
      country: "South Africa",
      continent: "Africa",
      region: "Southern Africa",
      latitude: -26.1337,
      longitude: 28.242,
      elevation_ft: 5558,
      runway_m: 4400,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1300, C: 180, F: 35 },
      slot_cost_usd: 2100,
      landing_fee_usd: 2500,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.07,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Africa’s busiest airport and South African Airways hub."
    },
    {
      icao: "HECA",
      iata: "CAI",
      city: "Cairo",
      country: "Egypt",
      continent: "Africa",
      region: "North Africa",
      latitude: 30.1219,
      longitude: 31.4056,
      elevation_ft: 382,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1200, C: 170, F: 40 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2400,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.06,
      slot_capacity: 240,
      aircraft_limit: "Heavy",
      notes: "Main hub for EgyptAir; connects Africa, Europe, and Middle East."
    },
    {
      icao: "HKJK",
      iata: "NBO",
      city: "Nairobi",
      country: "Kenya",
      continent: "Africa",
      region: "East Africa",
      latitude: -1.3192,
      longitude: 36.9278,
      elevation_ft: 5330,
      runway_m: 4117,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 900, C: 110, F: 20 },
      slot_cost_usd: 1600,
      landing_fee_usd: 2000,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 200,
      aircraft_limit: "Medium",
      notes: "Kenya Airways hub with regional and intercontinental ops."
    },
    {
      icao: "DNMM",
      iata: "LOS",
      city: "Lagos Murtala Muhammed",
      country: "Nigeria",
      continent: "Africa",
      region: "West Africa",
      latitude: 6.5774,
      longitude: 3.3211,
      elevation_ft: 135,
      runway_m: 3900,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1000, C: 130, F: 25 },
      slot_cost_usd: 1700,
      landing_fee_usd: 2100,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.04,
      slot_capacity: 220,
      aircraft_limit: "Medium",
      notes: "West Africa’s main commercial gateway."
    },
    {
      icao: "GMMN",
      iata: "CMN",
      city: "Casablanca",
      country: "Morocco",
      continent: "Africa",
      region: "North Africa",
      latitude: 33.3675,
      longitude: -7.58997,
      elevation_ft: 656,
      runway_m: 3720,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 850, C: 90, F: 15 },
      slot_cost_usd: 1500,
      landing_fee_usd: 1900,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 180,
      aircraft_limit: "Medium",
      notes: "Royal Air Maroc hub linking Africa and Europe."
    },
    {
      icao: "HAAB",
      iata: "ADD",
      city: "Addis Ababa",
      country: "Ethiopia",
      continent: "Africa",
      region: "East Africa",
      latitude: 8.9779,
      longitude: 38.7993,
      elevation_ft: 7656,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 950, C: 120, F: 20 },
      slot_cost_usd: 1600,
      landing_fee_usd: 2000,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.06,
      slot_capacity: 200,
      aircraft_limit: "Medium",
      notes: "Ethiopian Airlines main hub; strong intercontinental role."
    },
    {
      icao: "GOBD",
      iata: "DSS",
      city: "Dakar Blaise Diagne",
      country: "Senegal",
      continent: "Africa",
      region: "West Africa",
      latitude: 14.671,
      longitude: -17.073,
      elevation_ft: 294,
      runway_m: 3500,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 700, C: 90, F: 15 },
      slot_cost_usd: 1300,
      landing_fee_usd: 1600,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.04,
      slot_capacity: 160,
      aircraft_limit: "Medium",
      notes: "West African connector for Europe and America routes."
    },
    {
      icao: "FSIA",
      iata: "SEZ",
      city: "Mahé",
      country: "Seychelles",
      continent: "Africa",
      region: "Indian Ocean",
      latitude: -4.6743,
      longitude: 55.5218,
      elevation_ft: 10,
      runway_m: 2990,
      open_hrs: "24H",
      category: "Tourism",
      demand: { Y: 400, C: 40, F: 10 },
      slot_cost_usd: 1000,
      landing_fee_usd: 1400,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.02,
      slot_capacity: 100,
      aircraft_limit: "Medium",
      notes: "High-end leisure airport with limited capacity."
    }
  ], // end Africa
  /* =============================================================
     🌏 OCEANIA
     ============================================================= */
  Oceania: [
    {
      icao: "YSSY",
      iata: "SYD",
      city: "Sydney",
      country: "Australia",
      continent: "Oceania",
      region: "Australia East",
      latitude: -33.9461,
      longitude: 151.1772,
      elevation_ft: 21,
      runway_m: 3962,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 200, F: 50 },
      slot_cost_usd: 2400,
      landing_fee_usd: 2800,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.10,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "Qantas main hub; key Asia-Pacific gateway."
    },
    {
      icao: "YMML",
      iata: "MEL",
      city: "Melbourne",
      country: "Australia",
      continent: "Oceania",
      region: "Australia South",
      latitude: -37.6733,
      longitude: 144.843,
      elevation_ft: 434,
      runway_m: 3657,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1300, C: 160, F: 35 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2600,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.07,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Second largest airport in Australia; Virgin and Jetstar base."
    },
    {
      icao: "YBBN",
      iata: "BNE",
      city: "Brisbane",
      country: "Australia",
      continent: "Oceania",
      region: "Australia East",
      latitude: -27.3842,
      longitude: 153.1175,
      elevation_ft: 13,
      runway_m: 3500,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1000, C: 120, F: 20 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2300,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 220,
      aircraft_limit: "Medium",
      notes: "Main domestic and regional hub for Queensland."
    },
    {
      icao: "NZAA",
      iata: "AKL",
      city: "Auckland",
      country: "New Zealand",
      continent: "Oceania",
      region: "New Zealand",
      latitude: -37.0081,
      longitude: 174.7917,
      elevation_ft: 23,
      runway_m: 3635,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 900, C: 100, F: 20 },
      slot_cost_usd: 1800,
      landing_fee_usd: 2200,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.06,
      slot_capacity: 200,
      aircraft_limit: "Medium",
      notes: "Air New Zealand main base and Pacific connector."
    },
    {
      icao: "NZCH",
      iata: "CHC",
      city: "Christchurch",
      country: "New Zealand",
      continent: "Oceania",
      region: "New Zealand South",
      latitude: -43.4894,
      longitude: 172.531,
      elevation_ft: 123,
      runway_m: 3200,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 500, C: 60, F: 10 },
      slot_cost_usd: 1300,
      landing_fee_usd: 1600,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.03,
      slot_capacity: 120,
      aircraft_limit: "Medium",
      notes: "South Island international gateway and tourism hub."
    },
    {
      icao: "NFFN",
      iata: "NAN",
      city: "Nadi",
      country: "Fiji",
      continent: "Oceania",
      region: "Pacific Islands",
      latitude: -17.7554,
      longitude: 177.443,
      elevation_ft: 59,
      runway_m: 3200,
      open_hrs: "24H",
      category: "Tourism",
      demand: { Y: 400, C: 40, F: 10 },
      slot_cost_usd: 1100,
      landing_fee_usd: 1500,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.02,
      slot_capacity: 100,
      aircraft_limit: "Medium",
      notes: "Pacific leisure hub connecting Australia, NZ, and Hawaii."
    },
    {
      icao: "AYPY",
      iata: "POM",
      city: "Port Moresby",
      country: "Papua New Guinea",
      continent: "Oceania",
      region: "Melanesia",
      latitude: -9.443,
      longitude: 147.220,
      elevation_ft: 146,
      runway_m: 2850,
      open_hrs: "24H",
      category: "Regional Hub",
      demand: { Y: 350, C: 30, F: 5 },
      slot_cost_usd: 1000,
      landing_fee_usd: 1300,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.01,
      slot_capacity: 80,
      aircraft_limit: "Medium",
      notes: "PNG Air and Air Niugini main base; vital regional connectivity."
    }
  ], // end Oceania
  /* =============================================================
     🕌 MIDDLE EAST
     ============================================================= */
  MiddleEast: [
    /* === MIDDLE EAST AIRPORTS (ACS GLOBAL MAP v1.1 CLEAN — NO DUPLICATES) === */
{
  icao: "OMDB",
  iata: "DXB",
  city: "Dubai International",
  country: "United Arab Emirates",
  continent: "Asia",
  region: "Middle East",
  latitude: 25.252,
  longitude: 55.364,
  elevation_ft: 62,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 2400, C: 300, F: 80 },
  slot_cost_usd: 3500,
  landing_fee_usd: 3900,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.15,
  slot_capacity: 400,
  aircraft_limit: "Heavy",
  notes: "Emirates mega hub for intercontinental operations."
},
{
  icao: "OTHH",
  iata: "DOH",
  city: "Doha Hamad International",
  country: "Qatar",
  continent: "Asia",
  region: "Middle East",
  latitude: 25.273,
  longitude: 51.608,
  elevation_ft: 13,
  runway_m: 4850,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 2200, C: 280, F: 60 },
  slot_cost_usd: 3400,
  landing_fee_usd: 3800,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.13,
  slot_capacity: 380,
  aircraft_limit: "Heavy",
  notes: "Qatar Airways global hub; top-tier long-haul gateway."
},
{
  icao: "OMAA",
  iata: "AUH",
  city: "Abu Dhabi International",
  country: "United Arab Emirates",
  continent: "Asia",
  region: "Middle East",
  latitude: 24.433,
  longitude: 54.651,
  elevation_ft: 88,
  runway_m: 4100,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 2000, C: 250, F: 50 },
  slot_cost_usd: 3200,
  landing_fee_usd: 3600,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.10,
  slot_capacity: 320,
  aircraft_limit: "Heavy",
  notes: "Etihad Airways headquarters; key transcontinental link."
},
{
  icao: "OERK",
  iata: "RUH",
  city: "Riyadh King Khalid",
  country: "Saudi Arabia",
  continent: "Asia",
  region: "Middle East",
  latitude: 24.957,
  longitude: 46.698,
  elevation_ft: 2049,
  runway_m: 4205,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1600, C: 200, F: 30 },
  slot_cost_usd: 2800,
  landing_fee_usd: 3200,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.09,
  slot_capacity: 300,
  aircraft_limit: "Heavy",
  notes: "National gateway for Saudia; administrative capital hub."
},
{
  icao: "OEJN",
  iata: "JED",
  city: "Jeddah King Abdulaziz",
  country: "Saudi Arabia",
  continent: "Asia",
  region: "Middle East",
  latitude: 21.679,
  longitude: 39.156,
  elevation_ft: 48,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Major Hub",
  demand: { Y: 1800, C: 160, F: 25 },
  slot_cost_usd: 2600,
  landing_fee_usd: 3000,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.08,
  slot_capacity: 280,
  aircraft_limit: "Heavy",
  notes: "Gateway for Hajj and Umrah traffic; high seasonal volume."
},
{
  icao: "OKBK",
  iata: "KWI",
  city: "Kuwait International",
  country: "Kuwait",
  continent: "Asia",
  region: "Middle East",
  latitude: 29.226,
  longitude: 47.968,
  elevation_ft: 206,
  runway_m: 3400,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 900, C: 100, F: 20 },
  slot_cost_usd: 1900,
  landing_fee_usd: 2200,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 160,
  aircraft_limit: "Medium",
  notes: "Kuwait Airways main base with Gulf network focus."
},
{
  icao: "OJAI",
  iata: "AMM",
  city: "Amman Queen Alia",
  country: "Jordan",
  continent: "Asia",
  region: "Middle East",
  latitude: 31.722,
  longitude: 35.993,
  elevation_ft: 2395,
  runway_m: 3660,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 950, C: 100, F: 15 },
  slot_cost_usd: 2000,
  landing_fee_usd: 2300,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 160,
  aircraft_limit: "Medium",
  notes: "Royal Jordanian hub connecting Levant and Europe."
},
{
  icao: "LLBG",
  iata: "TLV",
  city: "Tel Aviv Ben Gurion",
  country: "Israel",
  continent: "Asia",
  region: "Middle East",
  latitude: 32.011,
  longitude: 34.886,
  elevation_ft: 135,
  runway_m: 3980,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1500, C: 160, F: 30 },
  slot_cost_usd: 2600,
  landing_fee_usd: 2900,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.07,
  slot_capacity: 260,
  aircraft_limit: "Heavy",
  notes: "El Al main base; major Middle East–Europe connector."
},
{
  icao: "OEDF",
  iata: "DMM",
  city: "Dammam King Fahd",
  country: "Saudi Arabia",
  continent: "Asia",
  region: "Middle East",
  latitude: 26.471,
  longitude: 49.797,
  elevation_ft: 72,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 1000, C: 100, F: 15 },
  slot_cost_usd: 1900,
  landing_fee_usd: 2200,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 160,
  aircraft_limit: "Medium",
  notes: "Eastern Saudi Arabia hub; cargo and Gulf traffic."
},
{
  icao: "OLBA",
  iata: "BEY",
  city: "Beirut Rafic Hariri",
  country: "Lebanon",
  continent: "Asia",
  region: "Middle East",
  latitude: 33.821,
  longitude: 35.488,
  elevation_ft: 87,
  runway_m: 3180,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 700, C: 80, F: 10 },
  slot_cost_usd: 1600,
  landing_fee_usd: 1900,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.03,
  slot_capacity: 120,
  aircraft_limit: "Medium",
  notes: "Lebanon’s primary international gateway."
},
{
  icao: "OOMS",
  iata: "MCT",
  city: "Muscat International",
  country: "Oman",
  continent: "Asia",
  region: "Middle East",
  latitude: 23.593,
  longitude: 58.284,
  elevation_ft: 15,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Primary Hub",
  demand: { Y: 1000, C: 110, F: 25 },
  slot_cost_usd: 2100,
  landing_fee_usd: 2400,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 200,
  aircraft_limit: "Heavy",
  notes: "Oman Air base; gateway between Asia and Africa."
},
{
  icao: "OSDI",
  iata: "DAM",
  city: "Damascus International",
  country: "Syria",
  continent: "Asia",
  region: "Middle East",
  latitude: 33.411,
  longitude: 36.515,
  elevation_ft: 2020,
  runway_m: 3600,
  open_hrs: "Limited",
  category: "International",
  demand: { Y: 400, C: 30, F: 5 },
  slot_cost_usd: 800,
  landing_fee_usd: 1100,
  fuel_usd_gal: 2.9,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.00,
  slot_capacity: 50,
  aircraft_limit: "Medium",
  notes: "Limited operations; potential future reactivation."
},
{
  icao: "OEMA",
  iata: "MED",
  city: "Medina Prince Mohammad bin Abdulaziz",
  country: "Saudi Arabia",
  continent: "Asia",
  region: "Middle East",
  latitude: 24.553,
  longitude: 39.705,
  elevation_ft: 2151,
  runway_m: 4000,
  open_hrs: "24H",
  category: "International",
  demand: { Y: 900, C: 80, F: 10 },
  slot_cost_usd: 1800,
  landing_fee_usd: 2100,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 140,
  aircraft_limit: "Medium",
  notes: "Holy city of Medina; large seasonal pilgrimage traffic."
},
{
  icao: "HESH",
  iata: "SSH",
  city: "Sharm El Sheikh",
  country: "Egypt",
  continent: "Africa",
  region: "Middle East",
  latitude: 27.977,
  longitude: 34.395,
  elevation_ft: 143,
  runway_m: 3081,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 800, C: 70, F: 10 },
  slot_cost_usd: 1600,
  landing_fee_usd: 1900,
  fuel_usd_gal: 2.9,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.06,
  slot_capacity: 140,
  aircraft_limit: "Medium",
  notes: "Major Red Sea leisure destination; charter heavy."
},
{
  icao: "OJAQ",
  iata: "AQJ",
  city: "Aqaba King Hussein",
  country: "Jordan",
  continent: "Asia",
  region: "Middle East",
  latitude: 29.611,
  longitude: 35.018,
  elevation_ft: 174,
  runway_m: 3000,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 500, C: 40, F: 5 },
  slot_cost_usd: 1200,
  landing_fee_usd: 1500,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Red Sea leisure airport; gateway to Petra."
},
{
  icao: "OOSA",
  iata: "SLL",
  city: "Salalah",
  country: "Oman",
  continent: "Asia",
  region: "Middle East",
  latitude: 17.038,
  longitude: 54.091,
  elevation_ft: 73,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 700, C: 60, F: 5 },
  slot_cost_usd: 1500,
  landing_fee_usd: 1800,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 120,
  aircraft_limit: "Medium",
  notes: "Coastal Oman leisure hub; popular during monsoon season."
},
{
  icao: "OIBB",
  iata: "BUZ",
  city: "Bushehr",
  country: "Iran",
  continent: "Asia",
  region: "Middle East",
  latitude: 28.945,
  longitude: 50.834,
  elevation_ft: 66,
  runway_m: 4200,
  open_hrs: "24H",
  category: "Regional",
  demand: { Y: 400, C: 30, F: 5 },
  slot_cost_usd: 1100,
  landing_fee_usd: 1300,
  fuel_usd_gal: 2.9,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.02,
  slot_capacity: 80,
  aircraft_limit: "Medium",
  notes: "Southern Iran coastal airport on the Persian Gulf."
},
{
  icao: "OIKB",
  iata: "BND",
  city: "Bandar Abbas",
  country: "Iran",
  continent: "Asia",
  region: "Middle East",
  latitude: 27.217,
  longitude: 56.377,
  elevation_ft: 22,
  runway_m: 3660,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 700, C: 60, F: 10 },
  slot_cost_usd: 1400,
  landing_fee_usd: 1700,
  fuel_usd_gal: 2.9,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.03,
  slot_capacity: 120,
  aircraft_limit: "Medium",
  notes: "Naval and commercial hub at the Strait of Hormuz."
},
{
  icao: "OMFJ",
  iata: "FJR",
  city: "Fujairah International",
  country: "United Arab Emirates",
  continent: "Asia",
  region: "Middle East",
  latitude: 25.112,
  longitude: 56.324,
  elevation_ft: 152,
  runway_m: 3750,
  open_hrs: "24H",
  category: "Regional",
  demand: { Y: 500, C: 40, F: 5 },
  slot_cost_usd: 1300,
  landing_fee_usd: 1600,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Cargo and training airport on UAE’s east coast."
},
{
  icao: "OMRK",
  iata: "RKT",
  city: "Ras Al Khaimah",
  country: "United Arab Emirates",
  continent: "Asia",
  region: "Middle East",
  latitude: 25.613,
  longitude: 55.938,
  elevation_ft: 102,
  runway_m: 3775,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 600, C: 50, F: 10 },
  slot_cost_usd: 1400,
  landing_fee_usd: 1700,
  fuel_usd_gal: 3.1,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 110,
  aircraft_limit: "Medium",
  notes: "UAE’s northern tourism destination with growing charter activity."
},
{
  icao: "OEKJ",
  iata: "YNB",
  city: "Yanbu",
  country: "Saudi Arabia",
  continent: "Asia",
  region: "Middle East",
  latitude: 24.144,
  longitude: 38.063,
  elevation_ft: 26,
  runway_m: 3050,
  open_hrs: "24H",
  category: "Regional",
  demand: { Y: 500, C: 30, F: 5 },
  slot_cost_usd: 1200,
  landing_fee_usd: 1500,
  fuel_usd_gal: 3.0,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.03,
  slot_capacity: 90,
  aircraft_limit: "Medium",
  notes: "Saudi Red Sea industrial and domestic hub."
},
{
  icao: "HEGN",
  iata: "HRG",
  city: "Hurghada International",
  country: "Egypt",
  continent: "Africa",
  region: "Middle East",
  latitude: 27.178,
  longitude: 33.799,
  elevation_ft: 52,
  runway_m: 4000,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 900, C: 70, F: 10 },
  slot_cost_usd: 1600,
  landing_fee_usd: 1900,
  fuel_usd_gal: 2.9,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.05,
  slot_capacity: 140,
  aircraft_limit: "Medium",
  notes: "Egypt’s top Red Sea resort airport; high charter volume."
},
{
  icao: "HELX",
  iata: "LXR",
  city: "Luxor International",
  country: "Egypt",
  continent: "Africa",
  region: "Middle East",
  latitude: 25.671,
  longitude: 32.706,
  elevation_ft: 294,
  runway_m: 3000,
  open_hrs: "24H",
  category: "Tourism",
  demand: { Y: 600, C: 50, F: 10 },
  slot_cost_usd: 1300,
  landing_fee_usd: 1600,
  fuel_usd_gal: 2.9,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 100,
  aircraft_limit: "Medium",
  notes: "Gateway to ancient Thebes and Nile tourism region."
},
{
  icao: "OIAW",
  iata: "AWZ",
  city: "Ahvaz International",
  country: "Iran",
  continent: "Asia",
  region: "Middle East",
  latitude: 31.34,
  longitude: 48.76,
  elevation_ft: 66,
  runway_m: 3400,
  open_hrs: "24H",
  category: "Regional Hub",
  demand: { Y: 700, C: 60, F: 10 },
  slot_cost_usd: 1400,
  landing_fee_usd: 1700,
  fuel_usd_gal: 2.9,
  ticket_fee_percent: 0.05,
  pax_growth_factor: 1.04,
  slot_capacity: 120,
  aircraft_limit: "Medium",
  notes: "Southwest Iran hub; domestic and Gulf flights."
}
  ], // end Middle East
  /* =============================================================
     🗺️ INDEX & GLOBAL ACCESS
     ============================================================= */
};

// === GLOBAL AIRPORT INDEX ===
const AirportIndex = {};
for (const cont in WorldAirportsACS) {
  WorldAirportsACS[cont].forEach((a) => {
    AirportIndex[a.icao] = a;
  });
}

// === FUNCTION: FIND AIRPORT BY ICAO CODE ===
function findAirport(icao) {
  return AirportIndex[icao.toUpperCase()] || null;
}

// === FUNCTION: SEARCH BY CITY OR COUNTRY ===
function searchAirports(keyword) {
  const key = keyword.toLowerCase();
  return Object.values(AirportIndex).filter(
    (a) =>
      a.city.toLowerCase().includes(key) ||
      a.country.toLowerCase().includes(key) ||
      a.iata.toLowerCase().includes(key) ||
      a.icao.toLowerCase().includes(key)
  );
}

// === FUNCTION: CALCULATE DISTANCE BETWEEN TWO AIRPORTS (NM) ===
function calcDistanceNM(icao1, icao2) {
  const a1 = findAirport(icao1);
  const a2 = findAirport(icao2);
  if (!a1 || !a2) return 0;
  const R = 3440;
  const toRad = (deg) => (deg * Math.PI) / 180;
  const dLat = toRad(a2.latitude - a1.latitude);
  const dLon = toRad(a2.longitude - a1.longitude);
  const lat1 = toRad(a1.latitude);
  const lat2 = toRad(a2.latitude);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2;
  return Math.round(R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)));
}

// === FUNCTION: ESTIMATE ROUTE ECONOMICS ===
function estimateRouteEconomics(icao1, icao2, demandClass) {
  const from = findAirport(icao1);
  const to = findAirport(icao2);
  if (!from || !to) return null;

  const dist = calcDistanceNM(icao1, icao2);
  const baseDemand = to.demand[demandClass] || 0;
  const fees = to.landing_fee_usd + to.slot_cost_usd + (dist * to.fuel_usd_gal * 0.2);
  const ticketRevenue =
    baseDemand * (demandClass === "Y" ? 200 : demandClass === "C" ? 550 : 1200);
  const profit = ticketRevenue - fees;

  return {
    distanceNM: dist,
    baseDemand,
    totalFeesUSD: fees.toFixed(0),
    estRevenueUSD: ticketRevenue.toFixed(0),
    estProfitUSD: profit.toFixed(0),
  };
}

// === FUNCTION: RANDOM AIRPORT (for AI testing / events) ===
function randomAirport() {
  const all = Object.values(AirportIndex);
  return all[Math.floor(Math.random() * all.length)];
}

// === DEBUG: PRINT SUMMARY (Optional) ===
console.log(
  `[ACS] WorldAirportsACS loaded: ${Object.keys(AirportIndex).length} airports indexed.`
);

/* =============================================================
   ✅ WorldAirportsACS.js — Global Civil & Commercial Database
   Version: 2.0 (Beta) — © 2025 Aviation Capital Simulator
   Author: ACS Dev Engineering Unit
   ============================================================= */
