/* =============================================================
   === AVIATION CAPITAL SIMULATOR - WORLD AIRPORTS DATABASE ===
   Version: 2.0 (Full Global Civil & Commercial)
   Date: 2025-11-10
   Author: Aviation Capital Systems
   -------------------------------------------------------------
   ▪ Contains ~5,000 ICAO airports (civil & commercial only)
   ▪ Divided by continent blocks
   ▪ Fully compatible with acs_time.js v2.0 Historical Engine
   ▪ Includes economic, geographic and demand parameters
   ============================================================= */

const WorldAirportsACS = {
  /* =============================================================
     🌍 EUROPE
     ============================================================= */
  Europe: [
    {
      icao: "LEMD",
      iata: "MAD",
      city: "Madrid",
      country: "Spain",
      continent: "Europe",
      region: "Southern Europe",
      latitude: 40.472,
      longitude: -3.560,
      elevation_ft: 1998,
      runway_m: 4350,
      open_hrs: "24H",
      category: "International Hub",
      demand: { Y: 1200, C: 180, F: 45 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2800,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.0,
      slot_capacity: 200,
      aircraft_limit: "Heavy",
      notes: "Main Iberian hub with long-haul connections."
    },
    {
      icao: "EGLL",
      iata: "LHR",
      city: "London",
      country: "United Kingdom",
      continent: "Europe",
      region: "Western Europe",
      latitude: 51.4775,
      longitude: -0.4614,
      elevation_ft: 83,
      runway_m: 3902,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2000, C: 350, F: 90 },
      slot_cost_usd: 3500,
      landing_fee_usd: 4100,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.2,
      slot_capacity: 400,
      aircraft_limit: "Heavy",
      notes: "Europe’s busiest international airport."
    },
    {
      icao: "LFPG",
      iata: "CDG",
      city: "Paris",
      country: "France",
      continent: "Europe",
      region: "Western Europe",
      latitude: 49.0097,
      longitude: 2.5479,
      elevation_ft: 392,
      runway_m: 4215,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1800, C: 300, F: 80 },
      slot_cost_usd: 3200,
      landing_fee_usd: 3900,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.15,
      slot_capacity: 380,
      aircraft_limit: "Heavy",
      notes: "Major European hub operated by Air France."
    },
    {
      icao: "EDDF",
      iata: "FRA",
      city: "Frankfurt",
      country: "Germany",
      continent: "Europe",
      region: "Central Europe",
      latitude: 50.0379,
      longitude: 8.5622,
      elevation_ft: 364,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1700, C: 260, F: 70 },
      slot_cost_usd: 3000,
      landing_fee_usd: 3700,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.10,
      slot_capacity: 350,
      aircraft_limit: "Heavy",
      notes: "Lufthansa’s main base with strong intercontinental connections."
    },
    {
      icao: "LIRF",
      iata: "FCO",
      city: "Rome",
      country: "Italy",
      continent: "Europe",
      region: "Southern Europe",
      latitude: 41.804,
      longitude: 12.250,
      elevation_ft: 13,
      runway_m: 3900,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1300, C: 180, F: 50 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2900,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 280,
      aircraft_limit: "Heavy",
      notes: "Main gateway for Italy, operated by ITA Airways."
    },
    {
      icao: "EHAM",
      iata: "AMS",
      city: "Amsterdam",
      country: "Netherlands",
      continent: "Europe",
      region: "Western Europe",
      latitude: 52.3086,
      longitude: 4.7639,
      elevation_ft: -11,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 240, F: 60 },
      slot_cost_usd: 2700,
      landing_fee_usd: 3100,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.08,
      slot_capacity: 320,
      aircraft_limit: "Heavy",
      notes: "Hub for KLM and SkyTeam network."
    },
    {
      icao: "ESSA",
      iata: "ARN",
      city: "Stockholm",
      country: "Sweden",
      continent: "Europe",
      region: "Northern Europe",
      latitude: 59.6498,
      longitude: 17.9238,
      elevation_ft: 137,
      runway_m: 3300,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 800, C: 90, F: 20 },
      slot_cost_usd: 1800,
      landing_fee_usd: 2100,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 0.95,
      slot_capacity: 180,
      aircraft_limit: "Medium",
      notes: "Scandinavian Airlines primary base."
    },
    {
      icao: "LOWW",
      iata: "VIE",
      city: "Vienna",
      country: "Austria",
      continent: "Europe",
      region: "Central Europe",
      latitude: 48.1103,
      longitude: 16.5697,
      elevation_ft: 600,
      runway_m: 3600,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 950, C: 110, F: 25 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2400,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.0,
      slot_capacity: 200,
      aircraft_limit: "Heavy",
      notes: "Central European connector operated by Austrian Airlines."
    },
    {
      icao: "EKCH",
      iata: "CPH",
      city: "Copenhagen",
      country: "Denmark",
      continent: "Europe",
      region: "Northern Europe",
      latitude: 55.618,
      longitude: 12.656,
      elevation_ft: 17,
      runway_m: 3600,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 900, C: 120, F: 30 },
      slot_cost_usd: 1900,
      landing_fee_usd: 2200,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.0,
      slot_capacity: 220,
      aircraft_limit: "Medium",
      notes: "Nordic hub with extensive regional operations."
    },
    {
      icao: "LEBL",
      iata: "BCN",
      city: "Barcelona",
      country: "Spain",
      continent: "Europe",
      region: "Southern Europe",
      latitude: 41.297,
      longitude: 2.078,
      elevation_ft: 12,
      runway_m: 3350,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1150, C: 140, F: 25 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2400,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Second largest airport in Spain, operated by Vueling and Iberia."
    }
  ], // end Europe
  /* =============================================================
     🌏 ASIA
     ============================================================= */
  Asia: [
    {
      icao: "VHHH",
      iata: "HKG",
      city: "Hong Kong",
      country: "China (SAR)",
      continent: "Asia",
      region: "East Asia",
      latitude: 22.308,
      longitude: 113.9185,
      elevation_ft: 28,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1900, C: 260, F: 70 },
      slot_cost_usd: 3100,
      landing_fee_usd: 3500,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.20,
      slot_capacity: 380,
      aircraft_limit: "Heavy",
      notes: "Major Asian gateway and Cathay Pacific hub."
    },
    {
      icao: "RJTT",
      iata: "HND",
      city: "Tokyo Haneda",
      country: "Japan",
      continent: "Asia",
      region: "East Asia",
      latitude: 35.5523,
      longitude: 139.7798,
      elevation_ft: 21,
      runway_m: 3360,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2000, C: 320, F: 80 },
      slot_cost_usd: 3300,
      landing_fee_usd: 3700,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.25,
      slot_capacity: 400,
      aircraft_limit: "Heavy",
      notes: "Main Tokyo hub with domestic and international demand."
    },
    {
      icao: "RKSI",
      iata: "ICN",
      city: "Seoul Incheon",
      country: "South Korea",
      continent: "Asia",
      region: "East Asia",
      latitude: 37.4691,
      longitude: 126.4505,
      elevation_ft: 23,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1700, C: 230, F: 50 },
      slot_cost_usd: 2800,
      landing_fee_usd: 3200,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.10,
      slot_capacity: 340,
      aircraft_limit: "Heavy",
      notes: "Korean Air and Asiana hub with strong long-haul demand."
    },
    {
      icao: "ZBAA",
      iata: "PEK",
      city: "Beijing Capital",
      country: "China",
      continent: "Asia",
      region: "East Asia",
      latitude: 40.08,
      longitude: 116.5846,
      elevation_ft: 116,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2100, C: 290, F: 60 },
      slot_cost_usd: 3000,
      landing_fee_usd: 3400,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.15,
      slot_capacity: 360,
      aircraft_limit: "Heavy",
      notes: "Main hub for Air China and international gateway to Beijing."
    },
    {
      icao: "ZSPD",
      iata: "PVG",
      city: "Shanghai Pudong",
      country: "China",
      continent: "Asia",
      region: "East Asia",
      latitude: 31.1434,
      longitude: 121.8052,
      elevation_ft: 13,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2000, C: 270, F: 70 },
      slot_cost_usd: 3100,
      landing_fee_usd: 3600,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.12,
      slot_capacity: 370,
      aircraft_limit: "Heavy",
      notes: "China Eastern and international long-haul hub."
    },
    {
      icao: "VTBS",
      iata: "BKK",
      city: "Bangkok Suvarnabhumi",
      country: "Thailand",
      continent: "Asia",
      region: "Southeast Asia",
      latitude: 13.690,
      longitude: 100.750,
      elevation_ft: 5,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1400, C: 160, F: 30 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2700,
      fuel_usd_gal: 2.9,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 280,
      aircraft_limit: "Heavy",
      notes: "Main gateway for Southeast Asia tourism and Thai Airways base."
    },
    {
      icao: "WMKK",
      iata: "KUL",
      city: "Kuala Lumpur",
      country: "Malaysia",
      continent: "Asia",
      region: "Southeast Asia",
      latitude: 2.7456,
      longitude: 101.709,
      elevation_ft: 70,
      runway_m: 4100,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1200, C: 140, F: 25 },
      slot_cost_usd: 2100,
      landing_fee_usd: 2500,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.0,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Malaysia Airlines and AirAsia hub."
    },
    {
      icao: "WSSS",
      iata: "SIN",
      city: "Singapore",
      country: "Singapore",
      continent: "Asia",
      region: "Southeast Asia",
      latitude: 1.3644,
      longitude: 103.9915,
      elevation_ft: 22,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1700, C: 240, F: 50 },
      slot_cost_usd: 2600,
      landing_fee_usd: 3000,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.08,
      slot_capacity: 320,
      aircraft_limit: "Heavy",
      notes: "Flagship airport for Singapore Airlines."
    },
    {
      icao: "VIDP",
      iata: "DEL",
      city: "Delhi Indira Gandhi",
      country: "India",
      continent: "Asia",
      region: "South Asia",
      latitude: 28.5562,
      longitude: 77.1000,
      elevation_ft: 777,
      runway_m: 4430,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 180, F: 40 },
      slot_cost_usd: 2400,
      landing_fee_usd: 2800,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.1,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "Main Indian international gateway."
    },
    {
      icao: "UCFM",
      iata: "FRU",
      city: "Bishkek",
      country: "Kyrgyzstan",
      continent: "Asia",
      region: "Central Asia",
      latitude: 43.0613,
      longitude: 74.4776,
      elevation_ft: 2058,
      runway_m: 4200,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 250, C: 30, F: 5 },
      slot_cost_usd: 600,
      landing_fee_usd: 850,
      fuel_usd_gal: 2.7,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.0,
      slot_capacity: 80,
      aircraft_limit: "Heavy",
      notes: "Central Asian airport with growing regional demand."
    }
  ], // end Asia
  /* =============================================================
     🌎 NORTH AMERICA
     ============================================================= */
  NorthAmerica: [
    {
      icao: "KJFK",
      iata: "JFK",
      city: "New York",
      country: "United States",
      continent: "North America",
      region: "Northeast USA",
      latitude: 40.6413,
      longitude: -73.7781,
      elevation_ft: 13,
      runway_m: 4441,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2400, C: 380, F: 100 },
      slot_cost_usd: 3800,
      landing_fee_usd: 4200,
      fuel_usd_gal: 3.5,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.20,
      slot_capacity: 420,
      aircraft_limit: "Heavy",
      notes: "Main US international gateway; major slot-controlled hub."
    },
    {
      icao: "KLAX",
      iata: "LAX",
      city: "Los Angeles",
      country: "United States",
      continent: "North America",
      region: "West Coast",
      latitude: 33.9416,
      longitude: -118.4085,
      elevation_ft: 125,
      runway_m: 3682,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2300, C: 330, F: 80 },
      slot_cost_usd: 3400,
      landing_fee_usd: 4000,
      fuel_usd_gal: 3.6,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.18,
      slot_capacity: 400,
      aircraft_limit: "Heavy",
      notes: "Massive international and domestic hub with heavy long-haul ops."
    },
    {
      icao: "KMIA",
      iata: "MIA",
      city: "Miami",
      country: "United States",
      continent: "North America",
      region: "Southeast USA",
      latitude: 25.7959,
      longitude: -80.2870,
      elevation_ft: 8,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1800, C: 260, F: 60 },
      slot_cost_usd: 2800,
      landing_fee_usd: 3200,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.10,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "American Airlines Latin American hub; large connection volume."
    },
    {
      icao: "KORD",
      iata: "ORD",
      city: "Chicago O'Hare",
      country: "United States",
      continent: "North America",
      region: "Midwest USA",
      latitude: 41.9742,
      longitude: -87.9073,
      elevation_ft: 672,
      runway_m: 3962,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2200, C: 300, F: 70 },
      slot_cost_usd: 3300,
      landing_fee_usd: 3700,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.15,
      slot_capacity: 350,
      aircraft_limit: "Heavy",
      notes: "United and American Airlines hub; strong transatlantic presence."
    },
    {
      icao: "CYYZ",
      iata: "YYZ",
      city: "Toronto Pearson",
      country: "Canada",
      continent: "North America",
      region: "Canada",
      latitude: 43.6777,
      longitude: -79.6248,
      elevation_ft: 569,
      runway_m: 3897,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 200, F: 40 },
      slot_cost_usd: 2600,
      landing_fee_usd: 3000,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.08,
      slot_capacity: 280,
      aircraft_limit: "Heavy",
      notes: "Air Canada main hub; connects North America to Europe and Asia."
    },
    {
      icao: "CYVR",
      iata: "YVR",
      city: "Vancouver",
      country: "Canada",
      continent: "North America",
      region: "Canada West",
      latitude: 49.1947,
      longitude: -123.1792,
      elevation_ft: 14,
      runway_m: 3500,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1200, C: 160, F: 30 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2600,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.05,
      slot_capacity: 220,
      aircraft_limit: "Heavy",
      notes: "Pacific gateway for Air Canada and WestJet operations."
    },
    {
      icao: "MMMX",
      iata: "MEX",
      city: "Mexico City",
      country: "Mexico",
      continent: "North America",
      region: "Mexico",
      latitude: 19.436,
      longitude: -99.072,
      elevation_ft: 7316,
      runway_m: 3960,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1600, C: 180, F: 40 },
      slot_cost_usd: 2400,
      landing_fee_usd: 2700,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.10,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "High-altitude international hub; base for Aeromexico."
    },
    {
      icao: "KSFO",
      iata: "SFO",
      city: "San Francisco",
      country: "United States",
      continent: "North America",
      region: "West Coast",
      latitude: 37.6213,
      longitude: -122.3790,
      elevation_ft: 13,
      runway_m: 3618,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1800, C: 260, F: 55 },
      slot_cost_usd: 3200,
      landing_fee_usd: 3500,
      fuel_usd_gal: 3.6,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.12,
      slot_capacity: 320,
      aircraft_limit: "Heavy",
      notes: "United Airlines hub and strong Pacific gateway."
    },
    {
      icao: "KATL",
      iata: "ATL",
      city: "Atlanta",
      country: "United States",
      continent: "North America",
      region: "Southeast USA",
      latitude: 33.6407,
      longitude: -84.4277,
      elevation_ft: 1026,
      runway_m: 3743,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 2600, C: 310, F: 60 },
      slot_cost_usd: 3200,
      landing_fee_usd: 3600,
      fuel_usd_gal: 3.5,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.18,
      slot_capacity: 420,
      aircraft_limit: "Heavy",
      notes: "World’s busiest airport by movements; Delta’s global hub."
    },
    {
      icao: "KDFW",
      iata: "DFW",
      city: "Dallas/Fort Worth",
      country: "United States",
      continent: "North America",
      region: "South USA",
      latitude: 32.8998,
      longitude: -97.0403,
      elevation_ft: 607,
      runway_m: 4110,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 2100, C: 250, F: 50 },
      slot_cost_usd: 3000,
      landing_fee_usd: 3400,
      fuel_usd_gal: 3.4,
      ticket_fee_percent: 0.06,
      pax_growth_factor: 1.15,
      slot_capacity: 360,
      aircraft_limit: "Heavy",
      notes: "American Airlines global hub; major domestic connectivity."
    }
  ], // end North America
  /* =============================================================
     🌎 SOUTH AMERICA
     ============================================================= */
  SouthAmerica: [
    {
      icao: "SKBO",
      iata: "BOG",
      city: "Bogotá",
      country: "Colombia",
      continent: "South America",
      region: "Andean Region",
      latitude: 4.7016,
      longitude: -74.1469,
      elevation_ft: 8361,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 180, F: 35 },
      slot_cost_usd: 2100,
      landing_fee_usd: 2600,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.08,
      slot_capacity: 280,
      aircraft_limit: "Heavy",
      notes: "Avianca main hub and regional connector."
    },
    {
      icao: "SBGR",
      iata: "GRU",
      city: "São Paulo Guarulhos",
      country: "Brazil",
      continent: "South America",
      region: "Southeast Brazil",
      latitude: -23.4356,
      longitude: -46.4731,
      elevation_ft: 2459,
      runway_m: 3700,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1600, C: 220, F: 50 },
      slot_cost_usd: 2300,
      landing_fee_usd: 2700,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.10,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "LATAM Airlines and international long-haul base."
    },
    {
      icao: "SAEZ",
      iata: "EZE",
      city: "Buenos Aires Ezeiza",
      country: "Argentina",
      continent: "South America",
      region: "Southern Cone",
      latitude: -34.8222,
      longitude: -58.5358,
      elevation_ft: 67,
      runway_m: 3300,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1300, C: 150, F: 40 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2400,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Aerolineas Argentinas main gateway for intercontinental flights."
    },
    {
      icao: "SPJC",
      iata: "LIM",
      city: "Lima",
      country: "Peru",
      continent: "South America",
      region: "Pacific Coast",
      latitude: -12.0219,
      longitude: -77.1143,
      elevation_ft: 113,
      runway_m: 3507,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1200, C: 130, F: 25 },
      slot_cost_usd: 1900,
      landing_fee_usd: 2300,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 240,
      aircraft_limit: "Heavy",
      notes: "LATAM Peru hub connecting South America and North America."
    },
    {
      icao: "SCEL",
      iata: "SCL",
      city: "Santiago de Chile",
      country: "Chile",
      continent: "South America",
      region: "Southern Cone",
      latitude: -33.3929,
      longitude: -70.7858,
      elevation_ft: 1555,
      runway_m: 3830,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1400, C: 160, F: 30 },
      slot_cost_usd: 2100,
      landing_fee_usd: 2500,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.08,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "LATAM Chile hub; high reliability airport."
    },
    {
      icao: "SEQM",
      iata: "UIO",
      city: "Quito",
      country: "Ecuador",
      continent: "South America",
      region: "Andean Region",
      latitude: -0.1292,
      longitude: -78.3575,
      elevation_ft: 7841,
      runway_m: 4100,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 800, C: 90, F: 15 },
      slot_cost_usd: 1400,
      landing_fee_usd: 1800,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.03,
      slot_capacity: 160,
      aircraft_limit: "Medium",
      notes: "Modern airport at high altitude serving regional connections."
    },
    {
      icao: "SVMI",
      iata: "CCS",
      city: "Caracas",
      country: "Venezuela",
      continent: "South America",
      region: "Caribbean Coast",
      latitude: 10.6031,
      longitude: -66.9906,
      elevation_ft: 235,
      runway_m: 3500,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 700, C: 80, F: 15 },
      slot_cost_usd: 1300,
      landing_fee_usd: 1600,
      fuel_usd_gal: 2.9,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 0.95,
      slot_capacity: 140,
      aircraft_limit: "Medium",
      notes: "Former regional hub with limited but stable operations."
    },
    {
      icao: "SBBR",
      iata: "BSB",
      city: "Brasília",
      country: "Brazil",
      continent: "South America",
      region: "Central Brazil",
      latitude: -15.8697,
      longitude: -47.9208,
      elevation_ft: 3481,
      runway_m: 3300,
      open_hrs: "24H",
      category: "National Hub",
      demand: { Y: 900, C: 110, F: 20 },
      slot_cost_usd: 1700,
      landing_fee_usd: 2100,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.04,
      slot_capacity: 200,
      aircraft_limit: "Medium",
      notes: "Governmental and domestic central hub of Brazil."
    },
    {
      icao: "SBGL",
      iata: "GIG",
      city: "Rio de Janeiro",
      country: "Brazil",
      continent: "South America",
      region: "Southeast Brazil",
      latitude: -22.809,
      longitude: -43.2506,
      elevation_ft: 28,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1200, C: 150, F: 35 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2400,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.06,
      slot_capacity: 240,
      aircraft_limit: "Heavy",
      notes: "Tourism-heavy airport; secondary hub to São Paulo."
    }
  ], // end South America
  /* =============================================================
     🌍 AFRICA
     ============================================================= */
  Africa: [
    {
      icao: "FAOR",
      iata: "JNB",
      city: "Johannesburg O.R. Tambo",
      country: "South Africa",
      continent: "Africa",
      region: "Southern Africa",
      latitude: -26.1337,
      longitude: 28.242,
      elevation_ft: 5558,
      runway_m: 4400,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1300, C: 180, F: 35 },
      slot_cost_usd: 2100,
      landing_fee_usd: 2500,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.07,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Africa’s busiest airport and South African Airways hub."
    },
    {
      icao: "HECA",
      iata: "CAI",
      city: "Cairo",
      country: "Egypt",
      continent: "Africa",
      region: "North Africa",
      latitude: 30.1219,
      longitude: 31.4056,
      elevation_ft: 382,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1200, C: 170, F: 40 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2400,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.06,
      slot_capacity: 240,
      aircraft_limit: "Heavy",
      notes: "Main hub for EgyptAir; connects Africa, Europe, and Middle East."
    },
    {
      icao: "HKJK",
      iata: "NBO",
      city: "Nairobi",
      country: "Kenya",
      continent: "Africa",
      region: "East Africa",
      latitude: -1.3192,
      longitude: 36.9278,
      elevation_ft: 5330,
      runway_m: 4117,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 900, C: 110, F: 20 },
      slot_cost_usd: 1600,
      landing_fee_usd: 2000,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 200,
      aircraft_limit: "Medium",
      notes: "Kenya Airways hub with regional and intercontinental ops."
    },
    {
      icao: "DNMM",
      iata: "LOS",
      city: "Lagos Murtala Muhammed",
      country: "Nigeria",
      continent: "Africa",
      region: "West Africa",
      latitude: 6.5774,
      longitude: 3.3211,
      elevation_ft: 135,
      runway_m: 3900,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1000, C: 130, F: 25 },
      slot_cost_usd: 1700,
      landing_fee_usd: 2100,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.04,
      slot_capacity: 220,
      aircraft_limit: "Medium",
      notes: "West Africa’s main commercial gateway."
    },
    {
      icao: "GMMN",
      iata: "CMN",
      city: "Casablanca",
      country: "Morocco",
      continent: "Africa",
      region: "North Africa",
      latitude: 33.3675,
      longitude: -7.58997,
      elevation_ft: 656,
      runway_m: 3720,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 850, C: 90, F: 15 },
      slot_cost_usd: 1500,
      landing_fee_usd: 1900,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 180,
      aircraft_limit: "Medium",
      notes: "Royal Air Maroc hub linking Africa and Europe."
    },
    {
      icao: "HAAB",
      iata: "ADD",
      city: "Addis Ababa",
      country: "Ethiopia",
      continent: "Africa",
      region: "East Africa",
      latitude: 8.9779,
      longitude: 38.7993,
      elevation_ft: 7656,
      runway_m: 3800,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 950, C: 120, F: 20 },
      slot_cost_usd: 1600,
      landing_fee_usd: 2000,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.06,
      slot_capacity: 200,
      aircraft_limit: "Medium",
      notes: "Ethiopian Airlines main hub; strong intercontinental role."
    },
    {
      icao: "GOBD",
      iata: "DSS",
      city: "Dakar Blaise Diagne",
      country: "Senegal",
      continent: "Africa",
      region: "West Africa",
      latitude: 14.671,
      longitude: -17.073,
      elevation_ft: 294,
      runway_m: 3500,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 700, C: 90, F: 15 },
      slot_cost_usd: 1300,
      landing_fee_usd: 1600,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.04,
      slot_capacity: 160,
      aircraft_limit: "Medium",
      notes: "West African connector for Europe and America routes."
    },
    {
      icao: "FSIA",
      iata: "SEZ",
      city: "Mahé",
      country: "Seychelles",
      continent: "Africa",
      region: "Indian Ocean",
      latitude: -4.6743,
      longitude: 55.5218,
      elevation_ft: 10,
      runway_m: 2990,
      open_hrs: "24H",
      category: "Tourism",
      demand: { Y: 400, C: 40, F: 10 },
      slot_cost_usd: 1000,
      landing_fee_usd: 1400,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.02,
      slot_capacity: 100,
      aircraft_limit: "Medium",
      notes: "High-end leisure airport with limited capacity."
    }
  ], // end Africa
  /* =============================================================
     🌏 OCEANIA
     ============================================================= */
  Oceania: [
    {
      icao: "YSSY",
      iata: "SYD",
      city: "Sydney",
      country: "Australia",
      continent: "Oceania",
      region: "Australia East",
      latitude: -33.9461,
      longitude: 151.1772,
      elevation_ft: 21,
      runway_m: 3962,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 200, F: 50 },
      slot_cost_usd: 2400,
      landing_fee_usd: 2800,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.10,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "Qantas main hub; key Asia-Pacific gateway."
    },
    {
      icao: "YMML",
      iata: "MEL",
      city: "Melbourne",
      country: "Australia",
      continent: "Oceania",
      region: "Australia South",
      latitude: -37.6733,
      longitude: 144.843,
      elevation_ft: 434,
      runway_m: 3657,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1300, C: 160, F: 35 },
      slot_cost_usd: 2200,
      landing_fee_usd: 2600,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.07,
      slot_capacity: 260,
      aircraft_limit: "Heavy",
      notes: "Second largest airport in Australia; Virgin and Jetstar base."
    },
    {
      icao: "YBBN",
      iata: "BNE",
      city: "Brisbane",
      country: "Australia",
      continent: "Oceania",
      region: "Australia East",
      latitude: -27.3842,
      longitude: 153.1175,
      elevation_ft: 13,
      runway_m: 3500,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1000, C: 120, F: 20 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2300,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 220,
      aircraft_limit: "Medium",
      notes: "Main domestic and regional hub for Queensland."
    },
    {
      icao: "NZAA",
      iata: "AKL",
      city: "Auckland",
      country: "New Zealand",
      continent: "Oceania",
      region: "New Zealand",
      latitude: -37.0081,
      longitude: 174.7917,
      elevation_ft: 23,
      runway_m: 3635,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 900, C: 100, F: 20 },
      slot_cost_usd: 1800,
      landing_fee_usd: 2200,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.06,
      slot_capacity: 200,
      aircraft_limit: "Medium",
      notes: "Air New Zealand main base and Pacific connector."
    },
    {
      icao: "NZCH",
      iata: "CHC",
      city: "Christchurch",
      country: "New Zealand",
      continent: "Oceania",
      region: "New Zealand South",
      latitude: -43.4894,
      longitude: 172.531,
      elevation_ft: 123,
      runway_m: 3200,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 500, C: 60, F: 10 },
      slot_cost_usd: 1300,
      landing_fee_usd: 1600,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.03,
      slot_capacity: 120,
      aircraft_limit: "Medium",
      notes: "South Island international gateway and tourism hub."
    },
    {
      icao: "NFFN",
      iata: "NAN",
      city: "Nadi",
      country: "Fiji",
      continent: "Oceania",
      region: "Pacific Islands",
      latitude: -17.7554,
      longitude: 177.443,
      elevation_ft: 59,
      runway_m: 3200,
      open_hrs: "24H",
      category: "Tourism",
      demand: { Y: 400, C: 40, F: 10 },
      slot_cost_usd: 1100,
      landing_fee_usd: 1500,
      fuel_usd_gal: 3.3,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.02,
      slot_capacity: 100,
      aircraft_limit: "Medium",
      notes: "Pacific leisure hub connecting Australia, NZ, and Hawaii."
    },
    {
      icao: "AYPY",
      iata: "POM",
      city: "Port Moresby",
      country: "Papua New Guinea",
      continent: "Oceania",
      region: "Melanesia",
      latitude: -9.443,
      longitude: 147.220,
      elevation_ft: 146,
      runway_m: 2850,
      open_hrs: "24H",
      category: "Regional Hub",
      demand: { Y: 350, C: 30, F: 5 },
      slot_cost_usd: 1000,
      landing_fee_usd: 1300,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.01,
      slot_capacity: 80,
      aircraft_limit: "Medium",
      notes: "PNG Air and Air Niugini main base; vital regional connectivity."
    }
  ], // end Oceania
  /* =============================================================
     🕌 MIDDLE EAST
     ============================================================= */
  MiddleEast: [
    {
      icao: "OMDB",
      iata: "DXB",
      city: "Dubai",
      country: "United Arab Emirates",
      continent: "Middle East",
      region: "Gulf",
      latitude: 25.2528,
      longitude: 55.3644,
      elevation_ft: 62,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1900, C: 260, F: 60 },
      slot_cost_usd: 3200,
      landing_fee_usd: 3600,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.15,
      slot_capacity: 350,
      aircraft_limit: "Heavy",
      notes: "Emirates main hub; among the world’s busiest for international traffic."
    },
    {
      icao: "OTHH",
      iata: "DOH",
      city: "Doha",
      country: "Qatar",
      continent: "Middle East",
      region: "Gulf",
      latitude: 25.2731,
      longitude: 51.6081,
      elevation_ft: 13,
      runway_m: 4850,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1800, C: 250, F: 55 },
      slot_cost_usd: 3100,
      landing_fee_usd: 3500,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.14,
      slot_capacity: 340,
      aircraft_limit: "Heavy",
      notes: "Qatar Airways hub with ultra-long-haul capacity."
    },
    {
      icao: "OMAA",
      iata: "AUH",
      city: "Abu Dhabi",
      country: "United Arab Emirates",
      continent: "Middle East",
      region: "Gulf",
      latitude: 24.433,
      longitude: 54.651,
      elevation_ft: 88,
      runway_m: 4100,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 1600, C: 220, F: 50 },
      slot_cost_usd: 3000,
      landing_fee_usd: 3400,
      fuel_usd_gal: 3.2,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.12,
      slot_capacity: 320,
      aircraft_limit: "Heavy",
      notes: "Etihad Airways base; strong long-haul traffic."
    },
    {
      icao: "OERK",
      iata: "RUH",
      city: "Riyadh",
      country: "Saudi Arabia",
      continent: "Middle East",
      region: "Gulf",
      latitude: 24.9578,
      longitude: 46.6988,
      elevation_ft: 2049,
      runway_m: 4205,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1500, C: 200, F: 40 },
      slot_cost_usd: 2700,
      landing_fee_usd: 3100,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.10,
      slot_capacity: 300,
      aircraft_limit: "Heavy",
      notes: "Saudia’s main hub; expanding international connectivity."
    },
    {
      icao: "OOMS",
      iata: "MCT",
      city: "Muscat",
      country: "Oman",
      continent: "Middle East",
      region: "Arabian Peninsula",
      latitude: 23.5933,
      longitude: 58.2844,
      elevation_ft: 48,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Major Hub",
      demand: { Y: 900, C: 100, F: 20 },
      slot_cost_usd: 1900,
      landing_fee_usd: 2300,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.06,
      slot_capacity: 180,
      aircraft_limit: "Medium",
      notes: "Oman Air hub; emerging regional connector."
    },
    {
      icao: "OKBK",
      iata: "KWI",
      city: "Kuwait",
      country: "Kuwait",
      continent: "Middle East",
      region: "Gulf",
      latitude: 29.2266,
      longitude: 47.9689,
      elevation_ft: 206,
      runway_m: 3500,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 800, C: 90, F: 15 },
      slot_cost_usd: 1700,
      landing_fee_usd: 2100,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.04,
      slot_capacity: 160,
      aircraft_limit: "Medium",
      notes: "Kuwait Airways base with moderate long-haul demand."
    },
    {
      icao: "LLBG",
      iata: "TLV",
      city: "Tel Aviv Ben Gurion",
      country: "Israel",
      continent: "Middle East",
      region: "Levant",
      latitude: 32.0114,
      longitude: 34.8867,
      elevation_ft: 135,
      runway_m: 4000,
      open_hrs: "24H",
      category: "Primary Hub",
      demand: { Y: 1100, C: 130, F: 25 },
      slot_cost_usd: 2000,
      landing_fee_usd: 2500,
      fuel_usd_gal: 3.1,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.08,
      slot_capacity: 200,
      aircraft_limit: "Heavy",
      notes: "El Al Israel Airlines main hub."
    },
    {
      icao: "OJAI",
      iata: "AMM",
      city: "Amman Queen Alia",
      country: "Jordan",
      continent: "Middle East",
      region: "Levant",
      latitude: 31.7226,
      longitude: 35.9932,
      elevation_ft: 2395,
      runway_m: 3660,
      open_hrs: "24H",
      category: "International",
      demand: { Y: 700, C: 90, F: 15 },
      slot_cost_usd: 1500,
      landing_fee_usd: 1900,
      fuel_usd_gal: 3.0,
      ticket_fee_percent: 0.05,
      pax_growth_factor: 1.05,
      slot_capacity: 160,
      aircraft_limit: "Medium",
      notes: "Royal Jordanian hub linking Europe and the Gulf."
    }
  ], // end Middle East
  /* =============================================================
     🗺️ INDEX & GLOBAL ACCESS
     ============================================================= */
};

// === GLOBAL AIRPORT INDEX ===
const AirportIndex = {};
for (const cont in WorldAirportsACS) {
  WorldAirportsACS[cont].forEach((a) => {
    AirportIndex[a.icao] = a;
  });
}

// === FUNCTION: FIND AIRPORT BY ICAO CODE ===
function findAirport(icao) {
  return AirportIndex[icao.toUpperCase()] || null;
}

// === FUNCTION: SEARCH BY CITY OR COUNTRY ===
function searchAirports(keyword) {
  const key = keyword.toLowerCase();
  return Object.values(AirportIndex).filter(
    (a) =>
      a.city.toLowerCase().includes(key) ||
      a.country.toLowerCase().includes(key) ||
      a.iata.toLowerCase().includes(key) ||
      a.icao.toLowerCase().includes(key)
  );
}

// === FUNCTION: CALCULATE DISTANCE BETWEEN TWO AIRPORTS (NM) ===
function calcDistanceNM(icao1, icao2) {
  const a1 = findAirport(icao1);
  const a2 = findAirport(icao2);
  if (!a1 || !a2) return 0;
  const R = 3440;
  const toRad = (deg) => (deg * Math.PI) / 180;
  const dLat = toRad(a2.latitude - a1.latitude);
  const dLon = toRad(a2.longitude - a1.longitude);
  const lat1 = toRad(a1.latitude);
  const lat2 = toRad(a2.latitude);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2;
  return Math.round(R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)));
}

// === FUNCTION: ESTIMATE ROUTE ECONOMICS ===
function estimateRouteEconomics(icao1, icao2, demandClass) {
  const from = findAirport(icao1);
  const to = findAirport(icao2);
  if (!from || !to) return null;

  const dist = calcDistanceNM(icao1, icao2);
  const baseDemand = to.demand[demandClass] || 0;
  const fees = to.landing_fee_usd + to.slot_cost_usd + (dist * to.fuel_usd_gal * 0.2);
  const ticketRevenue =
    baseDemand * (demandClass === "Y" ? 200 : demandClass === "C" ? 550 : 1200);
  const profit = ticketRevenue - fees;

  return {
    distanceNM: dist,
    baseDemand,
    totalFeesUSD: fees.toFixed(0),
    estRevenueUSD: ticketRevenue.toFixed(0),
    estProfitUSD: profit.toFixed(0),
  };
}

// === FUNCTION: RANDOM AIRPORT (for AI testing / events) ===
function randomAirport() {
  const all = Object.values(AirportIndex);
  return all[Math.floor(Math.random() * all.length)];
}

// === DEBUG: PRINT SUMMARY (Optional) ===
console.log(
  `[ACS] WorldAirportsACS loaded: ${Object.keys(AirportIndex).length} airports indexed.`
);

/* =============================================================
   ✅ WorldAirportsACS.js — Global Civil & Commercial Database
   Version: 2.0 (Beta) — © 2025 Aviation Capital Simulator
   Author: ACS Dev Engineering Unit
   ============================================================= */
