/* ============================================================
   === ACS COUNTRY HISTORY — FULL WORLD + AVIATION RELEVANCE ===
   ============================================================ */

const ACS_CountryHistory = [

  /* ===========================
     EUROPE — CURRENT STATES
     =========================== */
  { name: "Albania", start: 1912, end: null },
  { name: "Andorra", start: 1278, end: null },
  { name: "Armenia", start: 1991, end: null },
  { name: "Austria", start: 1918, end: null },
  { name: "Azerbaijan", start: 1991, end: null },
  { name: "Belarus", start: 1991, end: null },
  { name: "Belgium", start: 1830, end: null },
  { name: "Bosnia and Herzegovina", start: 1992, end: null },
  { name: "Bulgaria", start: 1908, end: null },
  { name: "Croatia", start: 1991, end: null },
  { name: "Cyprus", start: 1960, end: null },
  { name: "Czech Republic", start: 1993, end: null },
  { name: "Denmark", start: 1814, end: null },
  { name: "Estonia", start: 1991, end: null },
  { name: "Finland", start: 1917, end: null },
  { name: "France", start: 1792, end: null },
  { name: "Georgia", start: 1991, end: null },
  { name: "Germany", start: 1990, end: null },
  { name: "Greece", start: 1830, end: null },
  { name: "Hungary", start: 1918, end: null },
  { name: "Iceland", start: 1944, end: null },
  { name: "Ireland", start: 1922, end: null },
  { name: "Italy", start: 1861, end: null },
  { name: "Kazakhstan", start: 1991, end: null },
  { name: "Latvia", start: 1991, end: null },
  { name: "Lithuania", start: 1991, end: null },
  { name: "Luxembourg", start: 1815, end: null },
  { name: "Malta", start: 1964, end: null },
  { name: "Moldova", start: 1991, end: null },
  { name: "Montenegro", start: 2006, end: null },
  { name: "Netherlands", start: 1581, end: null },
  { name: "North Macedonia", start: 1991, end: null },
  { name: "Norway", start: 1905, end: null },
  { name: "Poland", start: 1918, end: null },
  { name: "Portugal", start: 1143, end: null },
  { name: "Romania", start: 1877, end: null },
  { name: "Serbia", start: 2006, end: null },
  { name: "Slovakia", start: 1993, end: null },
  { name: "Slovenia", start: 1991, end: null },
  { name: "Spain", start: 1479, end: null },
  { name: "Sweden", start: 1523, end: null },
  { name: "Switzerland", start: 1848, end: null },
  { name: "Turkey", start: 1923, end: null },
  { name: "Ukraine", start: 1991, end: null },
  { name: "United Kingdom", start: 1801, end: null },

  /* ===========================
     EUROPE — HISTORICAL STATES
     =========================== */
  { name: "East Germany", start: 1949, end: 1990 },
  { name: "West Germany", start: 1949, end: 1990 },
  { name: "Yugoslavia", start: 1918, end: 1992 },
  { name: "Czechoslovakia", start: 1918, end: 1992 },

  /* ===========================
     ASIA — CURRENT STATES
     =========================== */
  { name: "Afghanistan", start: 1919, end: null },
  { name: "Bahrain", start: 1971, end: null },
  { name: "Bangladesh", start: 1971, end: null },
  { name: "Bhutan", start: 1907, end: null },
  { name: "Brunei", start: 1984, end: null },
  { name: "Cambodia", start: 1953, end: null },
  { name: "China", start: 1949, end: null },
  { name: "India", start: 1947, end: null },
  { name: "Indonesia", start: 1945, end: null },
  { name: "Iran", start: 1925, end: null },
  { name: "Iraq", start: 1932, end: null },
  { name: "Israel", start: 1948, end: null },
  { name: "Japan", start: 1868, end: null },
  { name: "Jordan", start: 1946, end: null },
  { name: "Kuwait", start: 1961, end: null },
  { name: "Kyrgyzstan", start: 1991, end: null },
  { name: "Laos", start: 1953, end: null },
  { name: "Lebanon", start: 1943, end: null },
  { name: "Malaysia", start: 1963, end: null },
  { name: "Maldives", start: 1965, end: null },
  { name: "Mongolia", start: 1921, end: null },
  { name: "Myanmar", start: 1948, end: null },
  { name: "Nepal", start: 1768, end: null },
  { name: "North Korea", start: 1948, end: null },
  { name: "Oman", start: 1650, end: null },
  { name: "Pakistan", start: 1947, end: null },
  { name: "Philippines", start: 1946, end: null },
  { name: "Qatar", start: 1971, end: null },
  { name: "Saudi Arabia", start: 1932, end: null },
  { name: "Singapore", start: 1965, end: null },
  { name: "South Korea", start: 1948, end: null },
  { name: "Sri Lanka", start: 1948, end: null },
  { name: "Syria", start: 1946, end: null },
  { name: "Tajikistan", start: 1991, end: null },
  { name: "Thailand", start: 1238, end: null },
  { name: "Turkmenistan", start: 1991, end: null },
  { name: "United Arab Emirates", start: 1971, end: null },
  { name: "Uzbekistan", start: 1991, end: null },
  { name: "Vietnam", start: 1976, end: null },
  { name: "Yemen", start: 1990, end: null },

  /* ===========================
     ASIA — HISTORICAL STATES
     =========================== */
  { name: "British India", start: 1858, end: 1947 },
  { name: "East Pakistan", start: 1947, end: 1971 },
  { name: "South Vietnam", start: 1955, end: 1975 },

  /* ===========================
     MIDDLE EAST SPECIAL
     =========================== */
  { name: "United Arab Republic", start: 1958, end: 1971 },

  /* ===========================
     AFRICA — CURRENT STATES
     =========================== */
  { name: "Algeria", start: 1962, end: null },
  { name: "Angola", start: 1975, end: null },
  { name: "Benin", start: 1960, end: null },
  { name: "Botswana", start: 1966, end: null },
  { name: "Burkina Faso", start: 1984, end: null },
  { name: "Burundi", start: 1962, end: null },
  { name: "Cameroon", start: 1960, end: null },
  { name: "Cape Verde", start: 1975, end: null },
  { name: "Central African Republic", start: 1960, end: null },
  { name: "Chad", start: 1960, end: null },
  { name: "Comoros", start: 1975, end: null },
  { name: "Congo", start: 1960, end: null },
  { name: "Democratic Republic of the Congo", start: 1960, end: null },
  { name: "Djibouti", start: 1977, end: null },
  { name: "Egypt", start: 1922, end: null },
  { name: "Eritrea", start: 1993, end: null },
  { name: "Eswatini", start: 1968, end: null },
  { name: "Ethiopia", start: 1941, end: null },
  { name: "Gabon", start: 1960, end: null },
  { name: "Gambia", start: 1965, end: null },
  { name: "Ghana", start: 1957, end: null },
  { name: "Guinea", start: 1958, end: null },
  { name: "Guinea-Bissau", start: 1973, end: null },
  { name: "Ivory Coast", start: 1960, end: null },
  { name: "Kenya", start: 1963, end: null },
  { name: "Lesotho", start: 1966, end: null },
  { name: "Liberia", start: 1847, end: null },
  { name: "Libya", start: 1951, end: null },
  { name: "Madagascar", start: 1960, end: null },
  { name: "Malawi", start: 1964, end: null },
  { name: "Mali", start: 1960, end: null },
  { name: "Mauritania", start: 1960, end: null },
  { name: "Mauritius", start: 1968, end: null },
  { name: "Morocco", start: 1956, end: null },
  { name: "Mozambique", start: 1975, end: null },
  { name: "Namibia", start: 1990, end: null },
  { name: "Niger", start: 1960, end: null },
  { name: "Nigeria", start: 1960, end: null },
  { name: "Rwanda", start: 1962, end: null },
  { name: "Senegal", start: 1960, end: null },
  { name: "Seychelles", start: 1976, end: null },
  { name: "Sierra Leone", start: 1961, end: null },
  { name: "Somalia", start: 1960, end: null },
  { name: "South Africa", start: 1910, end: null },
  { name: "South Sudan", start: 2011, end: null },
  { name: "Sudan", start: 1956, end: 2011 },
  { name: "Tanzania", start: 1964, end: null },
  { name: "Togo", start: 1960, end: null },
  { name: "Tunisia", start: 1956, end: null },
  { name: "Uganda", start: 1962, end: null },
  { name: "Zambia", start: 1964, end: null },
  { name: "Zimbabwe", start: 1980, end: null },

  /* ===========================
     AMERICAS — CURRENT STATES
     =========================== */
  { name: "Argentina", start: 1816, end: null },
  { name: "Bolivia", start: 1825, end: null },
  { name: "Brazil", start: 1822, end: null },
  { name: "Canada", start: 1867, end: null },
  { name: "Chile", start: 1818, end: null },
  { name: "Colombia", start: 1886, end: null },
  { name: "Costa Rica", start: 1848, end: null },
  { name: "Cuba", start: 1902, end: null },
  { name: "Dominican Republic", start: 1844, end: null },
  { name: "Ecuador", start: 1830, end: null },
  { name: "El Salvador", start: 1841, end: null },
  { name: "Guatemala", start: 1821, end: null },
  { name: "Guyana", start: 1966, end: null },
  { name: "Haiti", start: 1804, end: null },
  { name: "Honduras", start: 1838, end: null },
  { name: "Jamaica", start: 1962, end: null },
  { name: "Mexico", start: 1821, end: null },
  { name: "Nicaragua", start: 1821, end: null },
  { name: "Panama", start: 1903, end: null },
  { name: "Paraguay", start: 1811, end: null },
  { name: "Peru", start: 1821, end: null },
  { name: "Suriname", start: 1975, end: null },
  { name: "Trinidad and Tobago", start: 1962, end: null },
  { name: "United States", start: 1776, end: null },
  { name: "Uruguay", start: 1828, end: null },
  { name: "Venezuela", start: 1830, end: null },

  /* ===========================
     AMERICAS — HISTORICAL
     =========================== */
  { name: "Gran Colombia", start: 1819, end: 1831 },

  /* ===========================
     OCEANIA — CURRENT STATES
     =========================== */
  { name: "Australia", start: 1901, end: null },
  { name: "Fiji", start: 1970, end: null },
  { name: "Kiribati", start: 1979, end: null },
  { name: "Marshall Islands", start: 1986, end: null },
  { name: "Micronesia", start: 1986, end: null },
  { name: "Nauru", start: 1968, end: null },
  { name: "New Zealand", start: 1907, end: null },
  { name: "Palau", start: 1994, end: null },
  { name: "Papua New Guinea", start: 1975, end: null },
  { name: "Samoa", start: 1962, end: null },
  { name: "Solomon Islands", start: 1978, end: null },
  { name: "Tonga", start: 1970, end: null },
  { name: "Tuvalu", start: 1978, end: null },
  { name: "Vanuatu", start: 1980, end: null }
];
