/* ============================================================
   🟦 ACS USED AIRCRAFT MARKET — BACKEND SYNC v1.0
   ------------------------------------------------------------
   File: engine/acs_used_market.js

   Purpose:
   - Frontend display only
   - Reads Used Aircraft Market from backend PostgreSQL
   - No localStorage authority
   - No local finance mutation
   - No local fleet creation
   - No system aircraft generation in browser

   Backend Authority:
   GET /v1/aircraft/used-market

   ACS Policy:
   - System seed generated by backend only
   - Purchased aircraft will NOT be replaced automatically
   - From 1951 onward, market becomes player/event driven
   ============================================================ */

console.log("🟦 ACS Used Aircraft Market — Backend Sync Loaded");

const ACS_API_BASE = "https://api.aviationcapitalsim.com";

let ACS_USED_MARKET_STATE = {
  loaded: false,
  loading: false,
  error: null,
  policy: null,
  seed_status: null,
  used_market: [],
  active_filter: "all"
};

/* ============================================================
   💰 MONEY FORMATTER SAFE
   ============================================================ */

function ACS_usedFormatUSD(value) {
  const n = Number(value || 0);
  if (!Number.isFinite(n)) return "$0";
  return "$" + Math.round(n).toLocaleString("en-US");
}

/* ============================================================
   🧼 HTML ESCAPE
   ============================================================ */

function ACS_escapeHTML(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

/* ============================================================
   🖼️ ACS USED MARKET IMAGE RESOLVER — BUY NEW SYNC v1.0
   ------------------------------------------------------------
   Purpose:
   - Use the same aircraft image logic as Buy New
   - Backend Used Market rows may not include "model"
   - Normalize from aircraft_name / model_key
   - JPG first because ACS aircraft library uses mostly JPG
   - Fallback to PNG, then placeholder
   ============================================================ */

function ACS_slugAircraftName(value) {
  return String(value || "")
    .toLowerCase()
    .trim()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function ACS_cleanUsedImageModelName(ac) {
  if (!ac) return "";

  const manufacturer = String(ac.manufacturer || "").trim();

  let model = String(
    ac.model ||
    ac.aircraft_model ||
    ac.aircraft_name ||
    ac.model_key ||
    ""
  ).trim();

  if (manufacturer) {
    const re = new RegExp(
      "^" + manufacturer.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "\\s+",
      "i"
    );
    model = model.replace(re, "").trim();
  }

  model = model
    .replace(/^boeing\s+/i, "")
    .replace(/^douglas\s+/i, "")
    .replace(/^lockheed\s+/i, "")
    .replace(/^airbus\s+/i, "")
    .replace(/^avro\s+/i, "")
    .replace(/^convair\s+/i, "")
    .replace(/^de\s+havilland\s+/i, "")
    .replace(/^vickers\s+/i, "")
    .replace(/^beechcraft\s+/i, "")
    .replace(/^fokker\s+/i, "")
    .replace(/^ford\s+/i, "")
    .replace(/^junkers\s+/i, "")
    .trim();

  return model;
}

/* ============================================================
   IMAGE ALIASES — ACS CANONICAL FILE NAMES
   ------------------------------------------------------------
   Same philosophy as Buy New.
   Add aliases here only when PostgreSQL names differ from
   existing ACS image filenames.
   ============================================================ */

const ACS_USED_IMAGE_MODEL_ALIASES = {
  /* Avro */
  "lancastrian": "lancastrian",

  /* Beechcraft */
  "model_18": "beechcraft_model_18",
  "beechcraft_model_18": "beechcraft_model_18",

  /* Boeing */
  "247": "boeing_247",
  "boeing_247": "boeing_247",
  "307_stratoliner": "boeing_307_stratoliner",
  "boeing_307_stratoliner": "boeing_307_stratoliner",
  "377_stratocruiser": "b_377_stratocruiser",
  "b_377_stratocruiser": "b_377_stratocruiser",
  "c_97_stratofreighter": "c_97_stratofreighter",

  /* Douglas */
  "dc_2": "dc_2",
  "dc_3": "dc_3",
  "dc_4": "dc_4",
  "dc_5": "dc_5",
  "dc_6": "dc_6",

  /* Lockheed */
  "model_9_orion": "model_9_orion",
  "l_10_electra": "l_10_electra",
  "l_12_electra_junior": "l_12_electra_junior",
  "l_14_super_electra": "l_14_super_electra",
  "l_18_lodestar": "l_18_lodestar",
  "l_049_constellation": "l_049_constellation",
  "l_649_constellation": "l_649_constellation",
  "l_749_constellation": "l_749_constellation",

  /* Convair */
  "cv_240": "cv_240",
  "convair_cv_240": "cv_240",

  /* de Havilland */
  "dh_84_dragon": "dh_84_dragon",
  "dh_86_express": "dh_86_express",
  "dh_89_dragon_rapide": "dh_89_dragon_rapide",
  "dh_91_albatross": "dh_91_albatross",
  "dh_95_flamingo": "dh_95_flamingo",
  "dh_104_dove": "dh_104_dove",
  "dh_114_heron": "dh_114_heron"
};

function ACS_getUsedAircraftManufacturerFolder(ac) {
  const manufacturer = String(ac?.manufacturer || "").trim();

  if (manufacturer.toLowerCase() === "de havilland") {
    return "de_havilland";
  }

  return manufacturer;
}

function getAircraftImage(ac) {
  if (!ac || !ac.manufacturer) {
    return "img/placeholder_aircraft.jpg";
  }

  const manufacturer = String(ac.manufacturer || "").trim();
  const manuFolder = ACS_getUsedAircraftManufacturerFolder(ac);

  const cleanModel = ACS_cleanUsedImageModelName(ac);
  const baseSlug = ACS_slugAircraftName(cleanModel);
  const manufacturerSlug = ACS_slugAircraftName(manufacturer);

  const modelKeySlug = ACS_slugAircraftName(ac.model_key || "");

  const aliasSlug =
    ACS_USED_IMAGE_MODEL_ALIASES[baseSlug] ||
    ACS_USED_IMAGE_MODEL_ALIASES[modelKeySlug] ||
    ACS_USED_IMAGE_MODEL_ALIASES[`${manufacturerSlug}_${baseSlug}`] ||
    ACS_USED_IMAGE_MODEL_ALIASES[`${manufacturerSlug}_${modelKeySlug}`] ||
    baseSlug ||
    modelKeySlug;

  const candidates = [];

  /* JPG first — ACS image library priority */
  candidates.push(`img/${manuFolder}/${aliasSlug}.jpg`);
  candidates.push(`img/${manuFolder}/${aliasSlug}.png`);

  /* fallback variants */
  candidates.push(`img/${manuFolder}/${baseSlug}.jpg`);
  candidates.push(`img/${manuFolder}/${baseSlug}.png`);

  candidates.push(`img/${manuFolder}/${modelKeySlug}.jpg`);
  candidates.push(`img/${manuFolder}/${modelKeySlug}.png`);

  candidates.push(`img/${manuFolder}/${manufacturerSlug}_${baseSlug}.jpg`);
  candidates.push(`img/${manuFolder}/${manufacturerSlug}_${baseSlug}.png`);

  /* root fallback */
  candidates.push(`img/${aliasSlug}.jpg`);
  candidates.push(`img/${aliasSlug}.png`);

  return candidates[0];
}

/* ============================================================
   🖼️ ACS IMAGE FALLBACK SYSTEM — BUY NEW SYNC
   ------------------------------------------------------------
   Purpose:
   - Try JPG / PNG variants
   - Avoid infinite 404 loops
   - Use JPG placeholder first
   ============================================================ */

function ACS_handleImageFallback(img) {
  if (!img) return;

  const currentSrc = img.getAttribute("src") || "";

  if (!img.dataset.fallbackStep) {
    img.dataset.fallbackStep = "0";
  }

  let step = Number(img.dataset.fallbackStep);
  step += 1;
  img.dataset.fallbackStep = String(step);

  if (step === 1 && currentSrc.endsWith(".jpg")) {
    img.src = currentSrc.replace(".jpg", ".png");
    return;
  }

  if (step === 2 && currentSrc.endsWith(".png")) {
    img.src = currentSrc.replace(".png", ".jpg");
    return;
  }

  img.onerror = null;
  img.src = "img/placeholder_aircraft.jpg";
}

/* ============================================================
   🌐 BACKEND LOAD — USED MARKET
   ============================================================ */

async function ACS_loadUsedMarketFromBackend() {
  ACS_USED_MARKET_STATE.loading = true;
  ACS_USED_MARKET_STATE.error = null;

  try {
    const response = await fetch(`${ACS_API_BASE}/v1/aircraft/used-market`, {
      method: "GET",
      credentials: "include",
      headers: {
        "Accept": "application/json"
      }
    });

    const data = await response.json().catch(() => null);

    if (!response.ok || !data || data.ok !== true) {
      throw new Error(data?.error || `USED_MARKET_HTTP_${response.status}`);
    }

    ACS_USED_MARKET_STATE.loaded = true;
    ACS_USED_MARKET_STATE.loading = false;
    ACS_USED_MARKET_STATE.error = null;
    ACS_USED_MARKET_STATE.policy = data.policy || null;
    ACS_USED_MARKET_STATE.seed_status = data.seed_status || null;
    ACS_USED_MARKET_STATE.used_market = Array.isArray(data.used_market)
      ? data.used_market
      : [];

    console.log("✅ ACS Used Market loaded from backend:", {
      count: ACS_USED_MARKET_STATE.used_market.length,
      seed_status: ACS_USED_MARKET_STATE.seed_status,
      policy: ACS_USED_MARKET_STATE.policy
    });

    return ACS_USED_MARKET_STATE.used_market;

  } catch (err) {
    ACS_USED_MARKET_STATE.loaded = false;
    ACS_USED_MARKET_STATE.loading = false;
    ACS_USED_MARKET_STATE.error = err.message;

    console.error("❌ ACS Used Market backend load failed:", err);

    return [];
  }
}

/* ============================================================
   === FILTER BAR — BACKEND DATA ===============================
   ============================================================ */

function buildFilterChips() {
  const bar = document.getElementById("filterBar");
  if (!bar) return;

  const list = ACS_USED_MARKET_STATE.used_market || [];

  const manufacturers = Array.from(
    new Set(
      list
        .map(ac => ac.manufacturer)
        .filter(Boolean)
    )
  ).sort();

  bar.innerHTML = "";

  const allChip = document.createElement("div");
  allChip.className = "chip active";
  allChip.dataset.manufacturer = "All";
  allChip.textContent = "All";
  bar.appendChild(allChip);

  manufacturers.forEach(m => {
    const chip = document.createElement("div");
    chip.className = "chip";
    chip.dataset.manufacturer = m;
    chip.textContent = m;
    bar.appendChild(chip);
  });

  bar.onclick = e => {
    const chip = e.target.closest(".chip");
    if (!chip) return;

    bar.querySelectorAll(".chip").forEach(c => c.classList.remove("active"));
    chip.classList.add("active");

    const filter = chip.dataset.manufacturer;
    ACS_USED_MARKET_STATE.active_filter = filter === "All" ? "all" : filter;

    renderUsedMarket(ACS_USED_MARKET_STATE.active_filter);
  };
}

/* ============================================================
   🧾 MARKET STATUS PANEL
   ============================================================ */

function ACS_renderUsedMarketStatus() {
  const grid = document.getElementById("usedGrid");
  if (!grid) return;

  const existing = document.getElementById("usedMarketStatusPanel");
  if (existing) existing.remove();

  const panel = document.createElement("div");
  panel.id = "usedMarketStatusPanel";
  panel.style.cssText = `
    width: 92%;
    margin: 0 auto 1.2rem;
    padding: 0.9rem 1rem;
    border: 1px solid rgba(255,179,0,0.35);
    border-radius: 12px;
    background: rgba(15,27,61,0.72);
    color: #dbe4ff;
    text-align: left;
    box-shadow: 0 0 14px rgba(0,0,0,0.25);
  `;

  const count = ACS_USED_MARKET_STATE.used_market.length;
  const policy = ACS_USED_MARKET_STATE.policy || {};
  const seed = ACS_USED_MARKET_STATE.seed_status || {};

  panel.innerHTML = `
    <div style="display:flex; flex-wrap:wrap; gap:12px; align-items:center; justify-content:space-between;">
      <div>
        <strong style="color:#ffb300;">ACS Used Aircraft Market</strong><br>
        <span style="font-size:0.86rem;color:#aebbe8;">
          Backend authority • Available listings: ${count}
        </span>
      </div>
      <div style="font-size:0.82rem;color:#aebbe8;">
        Seed: ${ACS_escapeHTML(seed.reason || "N/A")} |
        Replacement after purchase: ${policy.replacement_after_purchase === false ? "NO" : "N/A"} |
        Post-bootstrap generation: ${policy.post_bootstrap_system_generation === false ? "NO" : "N/A"}
      </div>
    </div>
  `;

  grid.parentNode.insertBefore(panel, grid);
}

/* ============================================================
   5) RENDER DE TARJETAS — BACKEND DATA
   ============================================================ */

function renderUsedMarket(filter = "all") {
  const grid = document.getElementById("usedGrid");
  if (!grid) return;

  grid.innerHTML = "";

  const list = ACS_USED_MARKET_STATE.used_market || [];

  const filtered = filter === "all"
    ? list
    : list.filter(ac => ac.manufacturer === filter);

  if (ACS_USED_MARKET_STATE.loading) {
    grid.innerHTML = `
      <div style="grid-column:1/-1; padding:2rem; color:#ffb300;">
        Loading Used Aircraft Market...
      </div>
    `;
    return;
  }

  if (ACS_USED_MARKET_STATE.error) {
    grid.innerHTML = `
      <div style="grid-column:1/-1; padding:2rem; color:#ff6b6b;">
        ❌ Used Aircraft Market unavailable.<br>
        <small>${ACS_escapeHTML(ACS_USED_MARKET_STATE.error)}</small>
      </div>
    `;
    return;
  }

  if (!filtered.length) {
    grid.innerHTML = `
      <div style="grid-column:1/-1; padding:2rem; color:#dbe4ff;">
        No aircraft available for this filter.
      </div>
    `;
    return;
  }

  filtered.forEach(ac => {
    const card = document.createElement("div");
    card.className = "used-card";

    const title = ac.aircraft_name ||
      `${ac.manufacturer || ""} ${ac.model_key || ""}`.trim();

    const yearBuilt = ac.year_built ?? "N/A";
    const hours = Number(ac.total_hours || 0);
    const cycles = Number(ac.total_cycles || 0);
    const condition = Number(ac.condition_pct || 0);
    const marketPrice = Number(ac.market_price || 0);
    const source = ac.market_source || "UNKNOWN";
    const broker = ac.remarketing_agent || "N/A";

    card.innerHTML = `
      <img src="${getAircraftImage(ac)}"
           onerror="ACS_handleImageFallback(this)"
           alt="${ACS_escapeHTML(title)}" />

      <h3>${ACS_escapeHTML(title)}</h3>

      <p>Manufacturer: ${ACS_escapeHTML(ac.manufacturer || "N/A")}</p>
      <p>Year Built: ${ACS_escapeHTML(yearBuilt)}</p>
      <p>Age: ${ACS_escapeHTML(ac.age_years ?? "N/A")} years</p>
      <p>Hours: ${hours.toLocaleString()}</p>
      <p>Cycles: ${cycles.toLocaleString()}</p>
      <p>Condition: ${condition.toFixed(0)}%</p>
      <p>Source: ${ACS_escapeHTML(source)}</p>
      <p>Broker: ${ACS_escapeHTML(broker)}</p>
      <p><b>Price: ${ACS_usedFormatUSD(marketPrice)}</b></p>

      <button class="ac-buy" onclick="buyUsed('${ac.id}')">
        BUY
      </button>
      <button class="ac-lease" onclick="leaseUsed('${ac.id}')">
        LEASE
      </button>
      <button class="ac-info" onclick="openInfo('${ac.id}')">
        INFO
      </button>
    `;

    grid.appendChild(card);
  });
}

/* ============================================================
   BUY USED — DISABLED UNTIL BACKEND PURCHASE ENDPOINT
   ============================================================ */

function buyUsed(id) {
  const ac = ACS_USED_MARKET_STATE.used_market.find(x => String(x.id) === String(id));

  if (!ac) {
    alert("❌ Aircraft not found in backend Used Market.");
    return;
  }

  alert(
    "🟦 ACS Backend Authority\n\n" +
    "Used aircraft purchase is now backend-controlled.\n" +
    "Next step: create POST /v1/aircraft/used-market/:id/buy.\n\n" +
    "No localStorage finance or fleet mutation was executed."
  );
}

/* ============================================================
   LEASE USED — DISABLED UNTIL BACKEND LEASE ENDPOINT
   ============================================================ */

function leaseUsed(id) {
  const ac = ACS_USED_MARKET_STATE.used_market.find(x => String(x.id) === String(id));

  if (!ac) {
    alert("❌ Aircraft not found in backend Used Market.");
    return;
  }

  alert(
    "🟦 ACS Backend Authority\n\n" +
    "Used aircraft leasing is not active yet.\n" +
    "Next phase: POST /v1/aircraft/used-market/:id/lease.\n\n" +
    "No localStorage leasing, finance or fleet mutation was executed."
  );
}

/* ============================================================
   MODAL INFO — BACKEND DATA
   ============================================================ */

function openInfo(id) {
  const ac = ACS_USED_MARKET_STATE.used_market.find(x => String(x.id) === String(id));
  if (!ac) return;

  const nameEl = document.getElementById("modalName");
  const detailsEl = document.getElementById("modalDetails");
  const modalEl = document.getElementById("infoModal");

  if (!nameEl || !detailsEl || !modalEl) return;

  const title = ac.aircraft_name ||
    `${ac.manufacturer || ""} ${ac.model_key || ""}`.trim();

  const hours = Number(ac.total_hours || 0);
  const cycles = Number(ac.total_cycles || 0);
  const condition = Number(ac.condition_pct || 0);

  nameEl.textContent = title;

  detailsEl.innerHTML = `
    <b>Aircraft Technical Snapshot</b><br>
    Manufacturer: ${ACS_escapeHTML(ac.manufacturer || "N/A")}<br>
    Model Key: ${ACS_escapeHTML(ac.model_key || "N/A")}<br>
    Serial Number: ${ACS_escapeHTML(ac.serial_number || "N/A")}<br>
    Previous Registration: ${ACS_escapeHTML(ac.previous_registration || "N/A")}<br>
    Previous Operator: ${ACS_escapeHTML(ac.previous_operator_name || ac.previous_operator || "N/A")}<br>
    <hr style="border-color:#444;">

    <b>Utilization</b><br>
    Year Built: ${ACS_escapeHTML(ac.year_built ?? "N/A")}<br>
    Age: ${ACS_escapeHTML(ac.age_years ?? "N/A")} years<br>
    Hours: ${hours.toLocaleString()}<br>
    Cycles: ${cycles.toLocaleString()}<br>
    Condition: ${condition.toFixed(0)}%<br>
    Maintenance Status: ${ACS_escapeHTML(ac.maintenance_status || "N/A")}<br>
    C-Check Due Hours: ${Number(ac.c_check_due_hours || 0).toLocaleString()}<br>
    C-Check Due Cycles: ${Number(ac.c_check_due_cycles || 0).toLocaleString()}<br>
    D-Check Due Date: ${ACS_escapeHTML(ac.d_check_due_date || "N/A")}<br>
    <hr style="border-color:#444;">

    <b>Market</b><br>
    Market Source: ${ACS_escapeHTML(ac.market_source || "N/A")}<br>
    Remarketing Agent: ${ACS_escapeHTML(ac.remarketing_agent || "N/A")}<br>
    Ownership Offer: ${ACS_escapeHTML(ac.ownership_offer_type || "N/A")}<br>
    Purchase Available: ${ac.available_for_purchase ? "YES" : "NO"}<br>
    Lease Available: ${ac.available_for_lease ? "YES" : "NO"}<br>
    Price: ${ACS_usedFormatUSD(ac.market_price)}<br>
  `;

  modalEl.style.display = "flex";
}

/* ============================================================
   MODAL CLOSE HELPERS
   ============================================================ */

function closeInfoModal() {
  const modalEl = document.getElementById("infoModal");
  if (modalEl) modalEl.style.display = "none";
}

function closeBuyModal() {
  const modalEl = document.getElementById("buyUsedModal");
  if (modalEl) modalEl.style.display = "none";
}

function closeLeaseModal() {
  const modalEl = document.getElementById("leaseUsedModal");
  if (modalEl) modalEl.style.display = "none";
}

/* ============================================================
   INIT
   ============================================================ */

document.addEventListener("DOMContentLoaded", async () => {
  const grid = document.getElementById("usedGrid");

  if (grid) {
    grid.innerHTML = `
      <div style="grid-column:1/-1; padding:2rem; color:#ffb300;">
        Loading Used Aircraft Market...
      </div>
    `;
  }

  await ACS_loadUsedMarketFromBackend();

  ACS_renderUsedMarketStatus();
  buildFilterChips();
  renderUsedMarket("all");
});

/* ============================================================
   GLOBAL EXPORTS
   ============================================================ */

window.ACS_USED_MARKET_STATE = ACS_USED_MARKET_STATE;
window.ACS_handleImageFallback = ACS_handleImageFallback;
window.buyUsed = buyUsed;
window.leaseUsed = leaseUsed;
window.openInfo = openInfo;
window.closeInfoModal = closeInfoModal;
window.closeBuyModal = closeBuyModal;
window.closeLeaseModal = closeLeaseModal;
